import type { Unit } from '../schema';
import { bars, fromCloses, fromHighs, fromLows } from '../helpers';

const RUBRIC = 'Original teaching chart graded with an instructor-defined rule, not a forecast. Synthetic data.';

export const unit04: Unit = {
  id: 'u4',
  number: 4,
  title: 'Read the chart',
  summary: 'Trends and ranges, swing points you can actually confirm, and what volume can and cannot say.',
  lessons: [
    {
      id: 'u4-trends',
      version: 1,
      unitId: 'u4',
      kind: 'lesson',
      title: 'Trends and ranges',
      objective: 'Describe a chart as an uptrend, downtrend or range, and spot when a pattern breaks.',
      minutes: 3,
      prerequisites: ['u3-checkpoint'],
      contentType: 'interpretive',
      steps: [
        {
          kind: 'concept',
          id: 'three-shapes',
          title: 'Three ways to describe the past',
          body:
            'An [[uptrend]] makes higher highs and higher lows. A [[downtrend]] makes lower highs and lower lows. A [[range]] moves sideways between a rough floor and ceiling.\n\nThese words describe what already happened. They are not promises about what happens next.',
          visual: {
            kind: 'candles',
            candles: fromCloses(20, [20.3, 20.6, 20.4, 20.8, 21.1, 20.9, 21.4, 21.7, 21.5, 22.0]),
            caption: 'Synthetic uptrend: pullbacks, but each low is above the last',
          },
        },
        {
          kind: 'exercise',
          id: 'describe',
          exercise: {
            id: 'u4-describe-downtrend',
            kind: 'choice',
            skills: ['trend-range'],
            prompt: 'How would you describe this chart?',
            visual: {
              kind: 'candles',
              candles: fromCloses(30, [29.6, 29.2, 29.5, 28.9, 28.5, 28.8, 28.2, 27.8, 28.1, 27.5]),
              caption: 'Synthetic chart, 10 candles',
            },
            options: [
              { id: 'down', text: 'A downtrend: lower highs and lower lows', correct: true, feedback: 'Yes. Each bounce peaks lower than the last, and each dip goes lower.' },
              { id: 'up', text: 'An uptrend, because some candles close higher', misconception: 'single-candle-trend', feedback: 'A few up candles are bounces. The trend is judged by the sequence of highs and lows.' },
              { id: 'range', text: 'A range', misconception: 'range-confusion', feedback: 'A range keeps returning to the same floor and ceiling. Here both keep falling.' },
            ],
            explanation: 'The highs and lows both step lower over time: a downtrend so far.',
            rubricNote: RUBRIC,
          },
        },
        {
          kind: 'exercise',
          id: 'pattern-break',
          exercise: {
            id: 'u4-higher-low-break',
            kind: 'candle-pick',
            skills: ['trend-range'],
            prompt: 'Each low was higher than the one before, until one candle broke the pattern. Tap the first candle whose low is lower than the previous candle’s low.',
            candles: fromLows([10.0, 10.3, 10.5, 10.8, 11.0, 11.3, 10.7, 10.9]),
            accept: [6],
            misconceptions: [
              { indices: [7], misconception: 'late-break', feedback: 'This candle’s low is higher than the one before it. The break came one candle earlier.' },
              { indices: [5], misconception: 'highest-low', feedback: 'This is the highest low so far; the pattern still held here.' },
            ],
            wrongFeedback: 'Compare each candle’s low (bottom of the wick) with the candle just before it.',
            explanation: 'Candle 7 has a low of $10.70, below the previous $11.30: the first lower low.',
            rubricNote: RUBRIC,
          },
        },
      ],
      recap: ['Uptrend: higher highs and lows. Downtrend: lower highs and lows. Range: sideways.', 'Judge by the sequence, not one candle.'],
      glossary: ['uptrend', 'downtrend', 'range'],
      sources: [],
      review: { skills: ['trend-range'] },
      help: {
        simpler: 'Look at the bottoms of the dips. Are they climbing, falling, or staying level? Then check the peaks the same way.',
        example: 'Peaks at $10, $11, $12 and dips at $9, $10, $11: an uptrend. Peaks at $10, $10, $10 and dips at $9, $9, $9: a range.',
      },
    },
    {
      id: 'u4-swings',
      version: 1,
      unitId: 'u4',
      kind: 'lesson',
      title: 'Swing points, and when you can know them',
      objective: 'Identify swing highs and lows that are confirmed using only candles already printed.',
      minutes: 4,
      prerequisites: ['u4-trends'],
      contentType: 'interpretive',
      steps: [
        {
          kind: 'concept',
          id: 'rule',
          title: 'A swing needs later candles',
          body:
            'A [[swing-high]] is a peak with lower highs on both sides. This course uses a simple rule: two lower highs before it and two after it.\n\nThat means a swing high is only confirmed two candles after it prints. In the moment, the newest high is just the newest high. A [[swing-low]] works the same way, upside down.',
        },
        {
          kind: 'exercise',
          id: 'swing-high',
          exercise: {
            id: 'u4-confirmed-swing-high',
            kind: 'candle-pick',
            skills: ['swing-points'],
            prompt: 'Using the two-candles-on-each-side rule, tap any confirmed swing high.',
            candles: fromHighs([10.2, 10.5, 10.9, 10.6, 10.4, 10.3, 10.7, 11.2, 10.8, 10.9, 11.4, 11.1]),
            accept: [2, 7],
            misconceptions: [
              { indices: [10], misconception: 'unconfirmed-swing', feedback: 'This is the highest candle, but only one candle has printed after it. It is not confirmed yet — the next candle could go higher.' },
              { indices: [9], misconception: 'one-sided-swing', feedback: 'The candle right after this one has a higher high, so it is not a peak.' },
            ],
            wrongFeedback: 'Look for a high with two lower highs on its left and two on its right.',
            explanation: 'Candles 3 and 8 each have two lower highs on both sides. Candle 11 is the tallest, but it cannot be confirmed yet.',
            rubricNote: RUBRIC,
          },
        },
        {
          kind: 'exercise',
          id: 'swing-low',
          exercise: {
            id: 'u4-confirmed-swing-low',
            kind: 'candle-pick',
            skills: ['swing-points'],
            prompt: 'Now tap any confirmed swing low, using the same two-candle rule.',
            candles: fromLows([10.0, 9.7, 9.5, 9.8, 10.0, 9.6, 9.2, 9.4, 9.7, 9.9, 9.5, 9.3]),
            accept: [2, 6],
            misconceptions: [
              { indices: [11], misconception: 'unconfirmed-swing', feedback: 'This is the newest candle. No candles have printed after it, so it cannot be a confirmed swing low.' },
              { indices: [10], misconception: 'one-sided-swing', feedback: 'The next candle made a lower low, so this is not a trough.' },
            ],
            wrongFeedback: 'Look for a low with two higher lows on each side.',
            explanation: 'Candles 3 and 7 each have two higher lows before and after. The latest candles cannot be confirmed yet.',
            rubricNote: RUBRIC,
          },
        },
      ],
      recap: ['Swing points need candles on both sides.', 'You can only confirm them after the fact — plan with that delay in mind.'],
      glossary: ['swing-high', 'swing-low', 'hindsight-bias'],
      sources: [],
      review: { skills: ['swing-points'] },
      help: {
        simpler: 'You can’t know you have reached the top of a hill until you have walked a little way down the other side.',
        example: 'Highs: 5, 6, 8, 7, 6. Candle 3 (8) is a swing high, but you only know that after candle 5 prints.',
      },
    },
    {
      id: 'u4-volume',
      version: 1,
      unitId: 'u4',
      kind: 'lesson',
      title: 'Volume and its limits',
      objective: 'Use volume as context without over-reading it.',
      minutes: 3,
      prerequisites: ['u4-swings'],
      contentType: 'interpretive',
      steps: [
        {
          kind: 'concept',
          id: 'what-volume-is',
          title: 'Volume counts shares, not sides',
          body:
            '[[volume]] counts shares traded in each period. A big move on high volume tells you many shares changed hands.\n\nIt does not tell you who “won”: every share bought was also sold. It also cannot tell you why people traded. Use it as context, not a verdict.',
          visual: {
            kind: 'candles',
            candles: fromCloses(12, [12.1, 12.05, 12.6, 12.55, 12.5, 12.6], 0.1, [800, 900, 3600, 1200, 900, 850]),
            showVolume: true,
            caption: 'Volume bars sit under each candle',
          },
        },
        {
          kind: 'exercise',
          id: 'volume-claim',
          exercise: {
            id: 'u4-volume-claim',
            kind: 'choice',
            skills: ['volume-context'],
            prompt: 'Price jumps on the highest volume of the day. Which conclusion does the data support?',
            options: [
              { id: 'a', text: 'Many shares changed hands during the jump.', correct: true, feedback: 'Yes. That is exactly what volume measures.' },
              { id: 'b', text: 'There were more buyers than sellers.', misconception: 'volume-buyers', feedback: 'Every trade has a buyer and a seller, so volume cannot count sides.' },
              { id: 'c', text: 'The move will continue.', misconception: 'volume-prediction', feedback: 'High volume moves reverse too. Volume describes activity, not the future.' },
              { id: 'd', text: 'Large institutions are buying.', misconception: 'volume-who', feedback: 'Volume does not identify who traded or why.' },
            ],
            explanation: 'Volume is the count of shares traded. Claims about sides, identities or the future need other evidence.',
            rubricNote: 'Instructor-defined rubric: accept only the claim the data directly supports.',
          },
        },
        {
          kind: 'exercise',
          id: 'volume-pick',
          exercise: {
            id: 'u4-busy-but-flat',
            kind: 'candle-pick',
            skills: ['volume-context'],
            prompt: 'Tap the candle that had unusually high volume even though price ended almost where it started.',
            candles: bars([
              [15.0, 15.2, 14.9, 15.1, 900],
              [15.1, 15.3, 15.0, 15.25, 1000],
              [15.25, 16.0, 15.2, 15.9, 3100],
              [15.9, 16.0, 15.7, 15.8, 1200],
              [15.8, 15.9, 15.6, 15.7, 950],
              [15.7, 16.1, 15.3, 15.72, 4200],
              [15.72, 15.9, 15.6, 15.85, 1100],
              [15.85, 15.95, 15.7, 15.8, 900],
            ]),
            accept: [5],
            misconceptions: [
              { indices: [2], misconception: 'big-move-volume', feedback: 'This candle had high volume, but price moved a lot — about $0.65 from open to close.' },
            ],
            wrongFeedback: 'Look for a tall volume bar under a candle whose open and close are nearly equal.',
            explanation: 'Candle 6 traded 4,200 shares but closed $0.02 above its open: lots of activity, little net change.',
            rubricNote: RUBRIC,
          },
        },
      ],
      recap: ['Volume = shares traded.', 'It cannot count buyers versus sellers or predict the next move.'],
      glossary: ['volume'],
      sources: [],
      review: { skills: ['volume-context'] },
      help: {
        simpler: 'Volume is like counting how many tickets were sold at a concert. It tells you it was busy, not whether people enjoyed it.',
        example: 'A candle with 5,000 shares traded and almost no change means many trades happened with no clear net movement.',
      },
    },
    {
      id: 'u4-checkpoint',
      version: 1,
      unitId: 'u4',
      kind: 'checkpoint',
      title: 'Unit 4 checkpoint',
      objective: 'Read new charts without using hindsight.',
      minutes: 3,
      prerequisites: ['u4-volume'],
      contentType: 'interpretive',
      steps: [
        { kind: 'concept', id: 'intro', title: 'New charts', body: 'New synthetic charts. Remember: describe what is there, and only confirm what the visible candles allow.' },
        {
          kind: 'exercise',
          id: 'cp-range',
          exercise: {
            id: 'u4-cp-range',
            kind: 'choice',
            skills: ['trend-range'],
            prompt: 'How would you describe this chart?',
            visual: {
              kind: 'candles',
              candles: fromCloses(15, [15.4, 15.1, 15.5, 15.0, 14.6, 15.0, 15.45, 15.05, 14.65, 15.1]),
              caption: 'Synthetic chart, 10 candles',
            },
            options: [
              { id: 'range', text: 'A range: price keeps returning between a similar floor and ceiling', correct: true, feedback: 'Yes. The peaks and dips stay at similar levels.' },
              { id: 'up', text: 'An uptrend', misconception: 'single-candle-trend', feedback: 'The last candle rose, but the peaks are not getting higher overall.' },
              { id: 'down', text: 'A downtrend', misconception: 'range-confusion', feedback: 'The dips are not getting lower overall; they return to a similar level.' },
            ],
            explanation: 'Highs cluster near $15.5–15.6 and lows near $14.5: sideways so far.',
            rubricNote: RUBRIC,
          },
        },
        {
          kind: 'exercise',
          id: 'cp-swing',
          exercise: {
            id: 'u4-cp-swing-high',
            kind: 'candle-pick',
            skills: ['swing-points'],
            prompt: 'Tap any confirmed swing high (two lower highs on each side).',
            candles: fromHighs([20.0, 20.4, 20.9, 20.5, 20.2, 20.6, 21.0, 20.7, 20.3, 20.8, 21.3, 21.0]),
            accept: [2, 6],
            misconceptions: [
              { indices: [10], misconception: 'unconfirmed-swing', feedback: 'Only one candle has printed after this one, so it is not confirmed yet.' },
              { indices: [9], misconception: 'one-sided-swing', feedback: 'The next candle is higher, so this is not a peak.' },
            ],
            wrongFeedback: 'Check two candles on each side.',
            explanation: 'Candles 3 and 7 are confirmed. Candle 11 is the tallest but still unconfirmed.',
            rubricNote: RUBRIC,
          },
        },
        {
          kind: 'exercise',
          id: 'cp-volume',
          exercise: {
            id: 'u4-cp-volume-claims',
            kind: 'categorize',
            skills: ['volume-context'],
            prompt: 'Which claims can volume data alone support?',
            categories: [
              { id: 'yes', label: 'Supported by volume' },
              { id: 'no', label: 'Not supported by volume alone' },
            ],
            items: [
              { id: 'count', text: '1,200 shares traded in this candle.', category: 'yes', feedback: 'That is the definition of volume.' },
              { id: 'busier', text: 'This period was busier than the one before it.', category: 'yes', feedback: 'Comparing volume across periods is supported.' },
              { id: 'buyers', text: 'Buyers outnumbered sellers.', category: 'no', feedback: 'Each trade has both a buyer and a seller.' },
              { id: 'big', text: 'Big investors are quietly accumulating.', category: 'no', feedback: 'Volume does not say who traded or why.' },
            ],
            explanation: 'Volume measures activity only.',
          },
        },
      ],
      recap: ['You described a range, confirmed swings without hindsight, and kept volume claims honest.'],
      glossary: ['range', 'swing-high', 'volume'],
      sources: [],
      review: { skills: ['trend-range', 'swing-points', 'volume-context'] },
      help: { simpler: 'Describe, don’t predict. Confirm a swing only when two candles on each side exist.', example: 'The newest peak is never a confirmed swing high.' },
    },
  ],
};
