import type { Unit } from '../schema';
import { bars, d, fromCloses } from '../helpers';

const ZONE_RUBRIC = 'Zones are approximate. Any placement inside the accepted area counts; this is an instructor-defined rubric on synthetic data, not a forecast.';

export const unit05: Unit = {
  id: 'u5',
  number: 5,
  title: 'Context, not certainty',
  summary: 'Support and resistance as areas, breakouts that fail, news and gaps, and the valid choice to wait.',
  lessons: [
    {
      id: 'u5-zones',
      version: 1,
      unitId: 'u5',
      kind: 'lesson',
      title: 'Support and resistance are areas',
      objective: 'Mark approximate zones where price has repeatedly paused.',
      minutes: 4,
      prerequisites: ['u4-checkpoint'],
      contentType: 'interpretive',
      steps: [
        {
          kind: 'concept',
          id: 'areas',
          title: 'Zones, not lines',
          body:
            '[[support]] is a price area where falling prices have often paused. [[resistance]] is an area where rising prices have often stalled.\n\nTreat them as zones, not exact lines. Price can poke through a zone and come back, or break through and keep going. Nothing about a zone guarantees a bounce.',
          visual: {
            kind: 'candles',
            candles: fromCloses(14.8, [15.2, 15.45, 15.1, 14.6, 14.2, 14.5, 15.0, 15.4, 15.2, 14.7, 14.25, 14.6]),
            zones: [
              { low: d(15.45), high: d(15.62), label: 'Resistance area' },
              { low: d(14.05), high: d(14.22), label: 'Support area' },
            ],
            caption: 'Synthetic range with approximate zones',
          },
        },
        {
          kind: 'exercise',
          id: 'resistance',
          exercise: {
            id: 'u5-place-resistance',
            kind: 'zone',
            skills: ['support-resistance'],
            prompt: 'Place the zone where rising prices have stalled most often.',
            candles: fromCloses(14.8, [15.2, 15.45, 15.1, 14.6, 14.2, 14.5, 15.0, 15.4, 15.2, 14.7, 14.25, 14.6, 15.1, 15.45, 15.0, 14.7]),
            accept: [{ low: d(15.3), high: d(15.75) }],
            zoneHeight: d(0.3),
            start: d(14.8),
            step: 5,
            misconceptions: [{ low: d(13.9), high: d(14.35), misconception: 'support-resistance-swap', feedback: 'That is where falling prices paused — a support area. Resistance is where rises stalled.' }],
            wrongFeedback: 'Look at where the tops of the candles keep reaching and turning back.',
            explanation: 'Three rallies stalled around $15.50–$15.60. A zone centered anywhere from about $15.30 to $15.75 captures it.',
            rubricNote: ZONE_RUBRIC,
          },
        },
        {
          kind: 'exercise',
          id: 'support',
          exercise: {
            id: 'u5-place-support',
            kind: 'zone',
            skills: ['support-resistance'],
            prompt: 'Place a support zone on this chart.',
            candles: fromCloses(21, [21.5, 21.8, 21.2, 20.6, 20.3, 20.7, 21.3, 21.7, 21.1, 20.5, 20.35, 20.8, 21.4, 21.1, 20.6, 20.4]),
            accept: [{ low: d(20.0), high: d(20.45) }],
            zoneHeight: d(0.3),
            start: d(21),
            step: 5,
            misconceptions: [{ low: d(21.6), high: d(22.1), misconception: 'support-resistance-swap', feedback: 'That is where rallies stalled — resistance. Support is below, where drops paused.' }],
            wrongFeedback: 'Look at where the bottoms of the dips keep turning back up.',
            explanation: 'Dips paused around $20.20–$20.30 three times. Centers from about $20.00 to $20.45 are accepted.',
            rubricNote: ZONE_RUBRIC,
          },
        },
      ],
      recap: ['Support: where falls paused. Resistance: where rises stalled.', 'They are approximate areas that can fail.'],
      glossary: ['support', 'resistance', 'range'],
      sources: [],
      review: { skills: ['support-resistance'] },
      help: {
        simpler: 'Think of a ball bouncing in a room: the floor and ceiling are where it keeps turning. But the “floor” here is soft, and sometimes the ball goes straight through.',
        example: 'Price dips to about $9.80, $9.85 and $9.75 before bouncing each time. A support zone around $9.75–$9.90 describes that.',
      },
    },
    {
      id: 'u5-breakouts',
      version: 1,
      unitId: 'u5',
      kind: 'lesson',
      title: 'Breakouts and failed breakouts',
      objective: 'Recognize a failed breakout and describe a breakout without overconfidence.',
      minutes: 4,
      prerequisites: ['u5-zones'],
      contentType: 'interpretive',
      steps: [
        {
          kind: 'concept',
          id: 'breakouts',
          title: 'Beyond the zone, for now',
          body:
            'A [[breakout]] is a move beyond a zone. Some continue. Many fall back inside: a [[failed-breakout]]. Those can trap people who bought the moment price poked through.\n\nWaiting for a close beyond the zone filters some false moves, but it means a worse entry price, and it still fails sometimes.',
        },
        {
          kind: 'exercise',
          id: 'failed',
          exercise: {
            id: 'u5-failed-breakout',
            kind: 'candle-pick',
            skills: ['breakouts'],
            prompt: 'The range ceiling was about $11.00. Price broke above it. Tap the first candle that closed back inside the range (below $11.00).',
            candles: bars([
              [10.2, 10.6, 10.1, 10.5],
              [10.5, 10.95, 10.4, 10.8],
              [10.8, 10.9, 10.3, 10.4],
              [10.4, 10.5, 10.05, 10.2],
              [10.2, 10.7, 10.1, 10.6],
              [10.6, 11.0, 10.5, 10.9],
              [10.9, 10.95, 10.5, 10.6],
              [10.6, 10.8, 10.3, 10.7],
              [10.7, 11.35, 10.65, 11.25],
              [11.25, 11.45, 11.0, 11.1],
              [11.1, 11.15, 10.6, 10.7],
              [10.7, 10.8, 10.3, 10.4],
            ]),
            accept: [10],
            misconceptions: [
              { indices: [8], misconception: 'breakout-candle', feedback: 'This is the breakout candle itself: it closed above $11.00.' },
              { indices: [9], misconception: 'wick-inside', feedback: 'Its low touched $11.00, but it closed at $11.10 — still above the ceiling.' },
              { indices: [11], misconception: 'late-read', feedback: 'This is inside the range, but the first close back inside came one candle earlier.' },
            ],
            wrongFeedback: 'Find the breakout candle, then look for the first close below $11.00 after it.',
            explanation: 'Candle 9 broke out and candle 10 held above, but candle 11 closed at $10.70, back inside: a failed breakout.',
            rubricNote: 'Instructor-defined rule: a failed breakout here means the first close back below the ceiling.',
          },
        },
        {
          kind: 'exercise',
          id: 'breakout-read',
          exercise: {
            id: 'u5-breakout-statement',
            kind: 'choice',
            skills: ['breakouts'],
            prompt: 'Price closes above resistance for the first time. Which statement is most accurate?',
            options: [
              { id: 'a', text: 'It is a breakout attempt. It may continue or fail, so any plan needs an exit if price falls back inside.', correct: true, feedback: 'Yes. You describe the move and plan for both outcomes.' },
              { id: 'b', text: 'A new uptrend is confirmed.', misconception: 'breakout-certainty', feedback: 'One close above a zone is not confirmation of anything lasting. Many breakouts fail.' },
              { id: 'c', text: 'It will come back to the zone, so it is safe to buy there later.', misconception: 'retest-certainty', feedback: 'Sometimes price returns to the zone, sometimes not. Neither is guaranteed.' },
            ],
            explanation: 'Breakouts are uncertain. A plan defines what failure looks like before entering.',
            rubricNote: 'Instructor-defined rubric: prefer the answer that states uncertainty and a plan.',
          },
        },
      ],
      recap: ['Breakouts can continue or fail.', 'A failed breakout closes back inside the zone.', 'Plan the exit before you enter.'],
      glossary: ['breakout', 'failed-breakout', 'resistance'],
      sources: [],
      review: { skills: ['breakouts'] },
      help: {
        simpler: 'Pushing through a door doesn’t mean you’ll stay in the next room. Sometimes you get pushed back.',
        example: 'Ceiling $50. Price closes at $50.40, then $49.60. That second close is back inside: the breakout failed, at least for now.',
      },
    },
    {
      id: 'u5-news-wait',
      version: 1,
      unitId: 'u5',
      kind: 'lesson',
      title: 'News, gaps and the choice to wait',
      objective: 'Treat waiting as a legitimate decision, and judge it by reasoning rather than outcome.',
      minutes: 4,
      prerequisites: ['u5-breakouts'],
      contentType: 'scenario',
      steps: [
        {
          kind: 'concept',
          id: 'news',
          title: 'Not every move needs you',
          body:
            'News can move prices suddenly, sometimes with a [[gap]]. Right after news, spreads can widen and prices can swing sharply.\n\nWaiting is a valid decision. You don’t need to trade every move. Passing costs nothing, and it protects you from acting on noise or excitement.',
        },
        {
          kind: 'exercise',
          id: 'news-decision',
          exercise: {
            id: 'u5-news-gap-decision',
            kind: 'decision',
            skills: ['waiting'],
            prompt: 'Choose an action and the reason that best supports it.',
            situation: 'A fictional company announces surprise news before the open. The stock opens 8% higher, the spread is three times wider than usual, and you have no plan written for this situation.',
            actions: [
              { id: 'buy', text: 'Buy now' },
              { id: 'wait', text: 'Wait' },
            ],
            reasons: [
              { id: 'r1', text: 'I have no plan for this, the wide spread makes entry expensive, and the move could reverse.', points: 2, supports: ['wait'], feedback: 'Strong reasoning: it names the missing plan, the cost and the uncertainty.' },
              { id: 'r2', text: 'Big news means it will keep going up.', points: 0, supports: ['buy'], misconception: 'news-certainty', feedback: 'News moves can reverse quickly. This reason is a prediction, not a plan.' },
              { id: 'r3', text: 'Gaps always fill, so it will come back down.', points: 1, supports: ['wait'], misconception: 'gaps-always-fill', feedback: 'Waiting is fine, but “gaps always fill” is itself a prediction. Many gaps never fill.' },
              { id: 'r4', text: 'If I don’t buy now I’ll miss out.', points: 0, supports: ['buy'], misconception: 'fomo', feedback: 'That is fear of missing out, not a reason tied to a plan.' },
            ],
            explanation: 'Good decisions are based on a plan and on costs you can see now, not on guesses about the next candle.',
            rubricNote: 'Graded on reasoning with an instructor-defined rubric. What the price did next is not part of the grade.',
          },
        },
        {
          kind: 'exercise',
          id: 'review-wait',
          exercise: {
            id: 'u5-review-waiting',
            kind: 'choice',
            skills: ['waiting'],
            prompt: 'You waited, and the stock rose another 5%. What is the best review of your decision?',
            options: [
              { id: 'a', text: 'Waiting was reasonable with no plan and a wide spread. One outcome doesn’t make it wrong.', correct: true, feedback: 'Yes. You judge the decision with the information you had.' },
              { id: 'b', text: 'I should always buy news gaps from now on.', misconception: 'outcome-bias', feedback: 'That changes your rules because of one result. One outcome is a tiny sample.' },
              { id: 'c', text: 'Waiting was a mistake because I missed profit.', misconception: 'outcome-bias', feedback: 'Missing a move is not a loss. Judge whether the reasoning was sound at the time.' },
            ],
            explanation: 'Separate the quality of a decision from the result of one instance.',
            rubricNote: 'Instructor-defined rubric on reasoning.',
          },
        },
      ],
      recap: ['News moves are fast and costly to chase.', 'Waiting is a real decision.', 'Judge decisions by reasoning, not by what happened next.'],
      glossary: ['gap', 'spread', 'fomo'],
      sources: ['finra-stop-orders'],
      review: { skills: ['waiting'] },
      help: {
        simpler: 'A bus that already left isn’t a loss. There will be another; running into traffic to catch it is the real risk.',
        example: 'You skip a move with no plan and it goes up. Next time, a similar move drops sharply. Both times, waiting without a plan was the same decision.',
      },
    },
    {
      id: 'u5-checkpoint',
      version: 1,
      unitId: 'u5',
      kind: 'checkpoint',
      title: 'Unit 5 checkpoint',
      objective: 'Apply zones, breakouts and waiting to new cases.',
      minutes: 3,
      prerequisites: ['u5-news-wait'],
      contentType: 'interpretive',
      steps: [
        { kind: 'concept', id: 'intro', title: 'New context', body: 'A new chart, a new breakout question and a new decision.' },
        {
          kind: 'exercise',
          id: 'cp-zone',
          exercise: {
            id: 'u5-cp-resistance',
            kind: 'zone',
            skills: ['support-resistance'],
            prompt: 'Place a resistance zone on this chart.',
            candles: fromCloses(40, [40.6, 41.1, 41.5, 41.0, 40.4, 40.0, 40.5, 41.2, 41.55, 41.1, 40.6, 40.9, 41.4, 41.5, 41.0]),
            accept: [{ low: d(41.4), high: d(41.85) }],
            zoneHeight: d(0.3),
            start: d(40.7),
            step: 5,
            misconceptions: [{ low: d(39.7), high: d(40.2), misconception: 'support-resistance-swap', feedback: 'That is where a drop paused: support. Resistance is where rallies stalled.' }],
            wrongFeedback: 'Where do the candle tops keep turning back?',
            explanation: 'Rallies stalled around $41.60 three times.',
            rubricNote: ZONE_RUBRIC,
          },
        },
        {
          kind: 'exercise',
          id: 'cp-breakout',
          exercise: {
            id: 'u5-cp-failed-breakout',
            kind: 'choice',
            skills: ['breakouts'],
            prompt: 'Price closes above a $30 ceiling, then the next two candles close at $29.70 and $29.40. What happened?',
            options: [
              { id: 'a', text: 'A failed breakout, at least for now.', correct: true, feedback: 'Yes. Price closed back inside the range.' },
              { id: 'b', text: 'A confirmed breakout.', misconception: 'breakout-certainty', feedback: 'Two closes back below the ceiling are the opposite of confirmation.' },
              { id: 'c', text: 'A new uptrend with a normal pullback.', misconception: 'breakout-certainty', feedback: 'Nothing here shows higher highs and higher lows yet.' },
            ],
            explanation: 'Closing back inside the zone after a breakout is what a failed breakout looks like.',
          },
        },
        {
          kind: 'exercise',
          id: 'cp-wait',
          exercise: {
            id: 'u5-cp-bored-decision',
            kind: 'decision',
            skills: ['waiting'],
            prompt: 'Choose an action and the best reason.',
            situation: 'Price is in the middle of a range, far from any zone. Your plan only trades near zones. You haven’t traded all session and feel bored.',
            actions: [
              { id: 'trade', text: 'Take a trade' },
              { id: 'wait', text: 'Wait' },
            ],
            reasons: [
              { id: 'r1', text: 'The setup in my plan isn’t there; boredom isn’t a reason to trade.', points: 2, supports: ['wait'], feedback: 'Exactly: the plan decides, not the mood.' },
              { id: 'r2', text: 'I need at least one trade per session to learn.', points: 0, supports: ['trade'], misconception: 'overtrading', feedback: 'Practicing patience is learning too. Trades without a setup teach bad habits.' },
              { id: 'r3', text: 'Something will probably happen soon.', points: 0, supports: ['trade'], misconception: 'prediction', feedback: 'That is a guess, not a setup.' },
              { id: 'r4', text: 'Waiting is safer because the price will drop.', points: 1, supports: ['wait'], misconception: 'prediction', feedback: 'Waiting is right, but the reason is a prediction. Base it on your plan.' },
            ],
            explanation: 'When your setup isn’t present, passing follows the plan.',
            rubricNote: 'Graded on reasoning with an instructor-defined rubric.',
          },
        },
      ],
      recap: ['You placed a new zone, recognized a failed breakout, and chose to wait for the right reason.'],
      glossary: ['resistance', 'failed-breakout'],
      sources: [],
      review: { skills: ['support-resistance', 'breakouts', 'waiting'] },
      help: { simpler: 'Zones are areas. Breakouts can fail. Waiting is allowed.', example: 'No setup? No trade.' },
    },
  ],
};
