import type { Unit } from '../schema';
import { bars, d } from '../helpers';

const RUBRIC = 'Candle definitions are standard charting conventions. The examples are original teaching data, not market records.';

export const unit03: Unit = {
  id: 'u3',
  number: 3,
  title: 'Candle Lab',
  summary: 'Open, high, low and close; bodies and wicks; and why one candle is not a forecast.',
  lessons: [
    {
      id: 'u3-ohlc',
      version: 1,
      unitId: 'u3',
      kind: 'lesson',
      title: 'Open, high, low, close',
      objective: 'Locate the four prices on a candle and match numbers to a candle.',
      minutes: 3,
      prerequisites: ['u2-checkpoint'],
      contentType: 'interpretive',
      steps: [
        {
          kind: 'concept',
          id: 'four-prices',
          title: 'One candle, four prices',
          body:
            'A candle summarizes one period of trading. [[open]]: the first price. [[high]]: the highest. [[low]]: the lowest. [[close]]: the last.\n\nThe thick [[candle-body]] runs between open and close. The thin [[wick]]s reach up to the high and down to the low.',
          visual: { kind: 'candle', ohlc: { open: d(10), high: d(10.8), low: d(9.6), close: d(10.5) }, showLabels: true, caption: 'Up candle: open $10.00, high $10.80, low $9.60, close $10.50' },
        },
        {
          kind: 'exercise',
          id: 'label',
          exercise: {
            id: 'u3-label-up-candle',
            kind: 'label-parts',
            skills: ['ohlc'],
            prompt: 'This candle closed higher than it opened. Label each marked point.',
            candle: { open: d(20), high: d(21.2), low: d(19.4), close: d(20.9) },
            markers: [
              { id: 'm1', anchor: 'high', correct: 'high' },
              { id: 'm2', anchor: 'bodyTop', correct: 'close' },
              { id: 'm3', anchor: 'bodyBottom', correct: 'open' },
              { id: 'm4', anchor: 'low', correct: 'low' },
            ],
            labels: [
              { id: 'open', text: 'Open' },
              { id: 'high', text: 'High' },
              { id: 'low', text: 'Low' },
              { id: 'close', text: 'Close' },
            ],
            wrongFeedback: 'In an up candle, the close is the top of the body and the open is the bottom. The wick tips are the high and low.',
            explanation: 'Up candle: body bottom = open, body top = close. Wick top = high, wick bottom = low.',
            rubricNote: RUBRIC,
          },
        },
        {
          kind: 'exercise',
          id: 'match',
          exercise: {
            id: 'u3-match-numbers',
            kind: 'candle-pick',
            skills: ['ohlc'],
            prompt: 'Which candle matches: open $10.00, high $10.60, low $9.80, close $10.40?',
            candles: bars([
              [10.4, 10.6, 9.8, 10.0],
              [10.0, 10.6, 9.8, 10.4],
              [10.0, 10.4, 9.8, 10.4],
              [10.0, 10.6, 9.6, 10.2],
            ]),
            accept: [1],
            misconceptions: [
              { indices: [0], misconception: 'open-close-swap', feedback: 'This one opened at $10.40 and closed at $10.00 — the reverse. It is a down candle.' },
              { indices: [2], misconception: 'no-upper-wick', feedback: 'This one’s high equals its close ($10.40), so it has no upper wick. The target high is $10.60.' },
              { indices: [3], misconception: 'close-mismatch', feedback: 'This closes at $10.20 and its low is $9.60. Check both ends again.' },
            ],
            wrongFeedback: 'Compare each candle’s four prices with the numbers in the question.',
            explanation: 'Candle 2 opens at $10.00, reaches $10.60, dips to $9.80 and closes at $10.40: an up candle with wicks on both ends.',
            rubricNote: RUBRIC,
          },
        },
      ],
      recap: ['Open = first, close = last, high = top of wick, low = bottom of wick.', 'In an up candle, the body runs from open (bottom) to close (top).'],
      glossary: ['open', 'high', 'low', 'close', 'candle-body', 'wick'],
      sources: [],
      review: { skills: ['ohlc'] },
      help: {
        simpler: 'Picture a thermometer for one hour: where it started, the hottest point, the coldest point, and where it ended. A candle draws those four numbers.',
        example: 'A day starts at $5.00, rises to $5.40, dips to $4.90 and ends at $5.20. Body: $5.00 to $5.20. Upper wick to $5.40, lower wick to $4.90.',
      },
    },
    {
      id: 'u3-bodies-wicks',
      version: 1,
      unitId: 'u3',
      kind: 'lesson',
      title: 'Bodies, wicks and unchanged candles',
      objective: 'Build candles with a given shape and explain what the shape records.',
      minutes: 4,
      prerequisites: ['u3-ohlc'],
      contentType: 'interpretive',
      steps: [
        {
          kind: 'concept',
          id: 'shapes',
          title: 'Reading the shape',
          body:
            'Close above open: an up candle, drawn hollow here and marked ▲. Close below open: a down candle, drawn filled and marked ▼. Close equal to open: an [[unchanged-candle]], with a flat line for a body.\n\nA long wick means price traveled far during the period and then came back.',
          visual: {
            kind: 'candles',
            candles: bars([
              [10, 10.6, 9.9, 10.5],
              [10.5, 10.6, 9.9, 10.0],
              [10.2, 10.6, 9.8, 10.2],
              [10.1, 10.9, 10.0, 10.2],
            ]),
            caption: 'Up, down, unchanged, and a candle with a long upper wick',
          },
        },
        {
          kind: 'exercise',
          id: 'build-down-wick',
          exercise: {
            id: 'u3-build-long-upper-wick',
            kind: 'candle-build',
            skills: ['candle-anatomy'],
            prompt: 'Build a down candle with a long upper wick: the upper wick should be at least half of the candle’s full range (high − low).',
            start: { open: d(10), high: d(10.2), low: d(9.8), close: d(10.1) },
            step: 5,
            rules: [
              { type: 'direction', value: 'down', failFeedback: 'A down candle closes below its open. Lower the close under the open.' },
              { type: 'upperWickMinRatio', ratio: 0.5, failFeedback: 'The upper wick is still short. Raise the high so the distance from the top of the body to the high is at least half the whole range.' },
            ],
            explanation: 'A down candle with a long upper wick records a period where price rose well above the open, then sold off to close lower.',
            rubricNote: RUBRIC,
          },
        },
        {
          kind: 'exercise',
          id: 'build-unchanged',
          exercise: {
            id: 'u3-build-unchanged',
            kind: 'candle-build',
            skills: ['candle-anatomy'],
            prompt: 'Build an unchanged candle: the close equals the open, with a wick on each side of at least 20% of the range.',
            start: { open: d(10), high: d(10.3), low: d(9.9), close: d(10.2) },
            step: 5,
            rules: [
              { type: 'direction', value: 'unchanged', failFeedback: 'The close must equal the open exactly for an unchanged candle.' },
              { type: 'upperWickMinRatio', ratio: 0.2, failFeedback: 'Add more upper wick: raise the high above the body.' },
              { type: 'lowerWickMinRatio', ratio: 0.2, failFeedback: 'Add more lower wick: lower the low below the body.' },
            ],
            explanation: 'An unchanged candle shows price moved during the period but ended where it started.',
            rubricNote: RUBRIC,
          },
        },
      ],
      recap: ['Up ▲ closes above the open; down ▼ closes below.', 'Unchanged: close = open.', 'Long wicks show where price traveled and came back.'],
      glossary: ['unchanged-candle', 'wick', 'candle-body'],
      sources: [],
      review: { skills: ['candle-anatomy'] },
      help: {
        simpler: 'The body shows where the period started and finished. The wicks show the extremes it reached along the way.',
        example: 'Open $8.00, high $8.60, low $7.95, close $7.98: a small down body with a long upper wick — price climbed, then gave it all back.',
      },
    },
    {
      id: 'u3-timeframes',
      version: 1,
      unitId: 'u3',
      kind: 'lesson',
      title: 'Timeframes, and why one candle is not a forecast',
      objective: 'Combine candles into a longer timeframe and avoid reading one candle as a prediction.',
      minutes: 4,
      prerequisites: ['u3-bodies-wicks'],
      contentType: 'interpretive',
      steps: [
        {
          kind: 'concept',
          id: 'combine',
          title: 'Same trading, different zoom',
          body:
            'A [[timeframe]] is how long one candle covers: 5 minutes, a day, a week. Three 5-minute candles combine into one 15-minute candle: the open of the first, the close of the last, the highest high and the lowest low.\n\nThe same move can look calm on one timeframe and dramatic on another.',
        },
        {
          kind: 'exercise',
          id: 'combine-high',
          exercise: {
            id: 'u3-combine-high',
            kind: 'numeric',
            skills: ['timeframes'],
            prompt: 'Combine these three 5-minute candles into one 15-minute candle. What is its high?',
            visual: {
              kind: 'candles',
              candles: bars([
                [10.0, 10.3, 9.9, 10.2],
                [10.2, 10.5, 10.1, 10.15],
                [10.15, 10.25, 9.8, 10.0],
              ]),
              caption: 'C1: O 10.00 H 10.30 L 9.90 C 10.20 · C2: O 10.20 H 10.50 L 10.10 C 10.15 · C3: O 10.15 H 10.25 L 9.80 C 10.00',
            },
            unit: 'usd',
            answer: d(10.5),
            tolerance: 0,
            inputLabel: 'Combined high, in dollars',
            misconceptions: [
              { value: d(10.25), misconception: 'last-candle-high', feedback: 'That is only the last candle’s high. The combined high is the highest of all three.' },
              { value: d(10.3), misconception: 'first-candle-high', feedback: 'That is the first candle’s high. Check the middle one.' },
              { value: d(10), misconception: 'close-not-high', feedback: '$10.00 is the combined close. The question asks for the high.' },
            ],
            wrongFeedback: 'Take the highest high across all three candles.',
            explanation: 'Highest of $10.30, $10.50, $10.25 is $10.50. The combined candle is O $10.00, H $10.50, L $9.80, C $10.00.',
          },
        },
        {
          kind: 'concept',
          id: 'not-forecast',
          title: 'One candle is a tiny sample',
          body:
            'A long lower wick shows that, during that period, price dipped and buyers pushed it back up. It does not tell you what the next candle will do. Treat a single candle as a clue to investigate, not a prediction.',
        },
        {
          kind: 'exercise',
          id: 'one-candle',
          exercise: {
            id: 'u3-one-candle-read',
            kind: 'choice',
            skills: ['timeframes'],
            prompt: 'A single 5-minute candle has a long lower wick. Which read is most defensible?',
            options: [
              { id: 'a', text: 'In those 5 minutes, price dipped and recovered. On its own, it says little about what comes next.', correct: true, feedback: 'Yes. It describes the past five minutes, nothing more.' },
              { id: 'b', text: 'Price will go up next.', misconception: 'one-candle-prediction', feedback: 'One candle is not a forecast. Plenty of long-wick candles are followed by further falls.' },
              { id: 'c', text: 'Buyers have taken control for the day.', misconception: 'overreach', feedback: 'Five minutes cannot tell you about the whole day. Look at a longer timeframe for more context.' },
            ],
            explanation: 'Candles describe what happened in a period. Patterns are hypotheses to test, not reliable predictions.',
            rubricNote: 'Instructor-defined rubric: the accepted answer is the one that does not claim more than the data shows.',
          },
        },
      ],
      recap: ['Combined candle: first open, last close, highest high, lowest low.', 'Timeframe changes how a move looks.', 'One candle is not a prediction.'],
      glossary: ['timeframe', 'wick'],
      sources: [],
      review: { skills: ['timeframes'] },
      help: {
        simpler: 'Zooming out is like summarizing three short videos as one clip: it starts where the first began, ends where the last ended, and includes the biggest high and lowest low from all three.',
        example: 'Candles with highs $5.10, $5.30, $5.20 and lows $4.90, $5.00, $4.80 combine into one with high $5.30 and low $4.80.',
      },
    },
    {
      id: 'u3-checkpoint',
      version: 1,
      unitId: 'u3',
      kind: 'checkpoint',
      title: 'Unit 3 checkpoint',
      objective: 'Read and build candles you have not seen before.',
      minutes: 3,
      prerequisites: ['u3-timeframes'],
      contentType: 'interpretive',
      steps: [
        { kind: 'concept', id: 'intro', title: 'New candles', body: 'This time the candle closes lower, the shape is different, and the numbers are new.' },
        {
          kind: 'exercise',
          id: 'cp-label-down',
          exercise: {
            id: 'u3-cp-label-down',
            kind: 'label-parts',
            skills: ['ohlc'],
            prompt: 'This candle closed lower than it opened. Label each marked point.',
            candle: { open: d(15.6), high: d(15.9), low: d(14.8), close: d(15.1) },
            markers: [
              { id: 'm1', anchor: 'bodyTop', correct: 'open' },
              { id: 'm2', anchor: 'bodyBottom', correct: 'close' },
              { id: 'm3', anchor: 'high', correct: 'high' },
              { id: 'm4', anchor: 'low', correct: 'low' },
            ],
            labels: [
              { id: 'open', text: 'Open' },
              { id: 'high', text: 'High' },
              { id: 'low', text: 'Low' },
              { id: 'close', text: 'Close' },
            ],
            wrongFeedback: 'In a down candle the open is the top of the body and the close is the bottom.',
            explanation: 'Down candle: body top = open, body bottom = close.',
            rubricNote: RUBRIC,
          },
        },
        {
          kind: 'exercise',
          id: 'cp-build-hammer',
          exercise: {
            id: 'u3-cp-build-long-lower-wick',
            kind: 'candle-build',
            skills: ['candle-anatomy'],
            prompt: 'Build an up candle with a long lower wick (at least 60% of the range) and a small upper wick (no more than 10%).',
            start: { open: d(20), high: d(20.5), low: d(19.8), close: d(20.2) },
            step: 5,
            rules: [
              { type: 'direction', value: 'up', failFeedback: 'An up candle closes above its open.' },
              { type: 'lowerWickMinRatio', ratio: 0.6, failFeedback: 'Make the lower wick longer: lower the low, or move the body higher.' },
              { type: 'upperWickMaxRatio', ratio: 0.1, failFeedback: 'The upper wick is too long. Bring the high closer to the top of the body.' },
            ],
            explanation: 'This shape records a period where price fell well below the open, then recovered to close higher, near the high.',
            rubricNote: RUBRIC,
          },
        },
        {
          kind: 'exercise',
          id: 'cp-combine-low',
          exercise: {
            id: 'u3-cp-combine-low',
            kind: 'numeric',
            skills: ['timeframes'],
            prompt: 'Four 15-minute candles have lows of $31.40, $31.10, $31.25 and $31.60, and the first opens at $31.50. What is the low of the combined 1-hour candle?',
            unit: 'usd',
            answer: d(31.1),
            tolerance: 0,
            inputLabel: 'Combined low, in dollars',
            misconceptions: [
              { value: d(31.6), misconception: 'last-candle-low', feedback: 'That is the last candle’s low. Use the lowest across all four.' },
              { value: d(31.5), misconception: 'open-not-low', feedback: '$31.50 is the combined open, not the low.' },
            ],
            wrongFeedback: 'The combined low is the lowest low of the four.',
            explanation: 'Lowest of the four lows is $31.10.',
          },
        },
      ],
      recap: ['You labeled a down candle, built a new shape, and combined timeframes.'],
      glossary: ['open', 'close', 'wick', 'timeframe'],
      sources: [],
      review: { skills: ['ohlc', 'candle-anatomy', 'timeframes'] },
      help: { simpler: 'Up candle: open at the bottom of the body. Down candle: open at the top.', example: 'Open $9, close $8: a down candle, open on top.' },
    },
  ],
};
