import type { Unit } from '../schema';

const REASONING = 'Graded on reasoning with an instructor-defined rubric. The result of the trade is not part of the grade.';

export const unit09: Unit = {
  id: 'u9',
  number: 9,
  title: 'Journal and review',
  summary: 'Record decisions, judge them separately from outcomes, and read small samples of results honestly.',
  lessons: [
    {
      id: 'u9-journal',
      version: 1,
      unitId: 'u9',
      kind: 'lesson',
      title: 'What a journal records',
      objective: 'Know which facts to record and calculate a trade’s R-multiple.',
      minutes: 4,
      prerequisites: ['u8-checkpoint'],
      contentType: 'scenario',
      steps: [
        {
          kind: 'concept',
          id: 'record',
          title: 'The facts, then the thinking',
          body:
            'A [[journal]] entry records the plan (entry, stop, target, reason), what happened (fills, costs, exit reason), and a short reflection.\n\nThe [[r-multiple]] compares the result with the risk you planned: net profit or loss ÷ initial risk. Risk is fixed when you enter, so moving the stop later can’t make a trade look better.',
        },
        {
          kind: 'exercise',
          id: 'calc-r',
          exercise: {
            id: 'u9-r-multiple',
            kind: 'numeric',
            skills: ['journaling'],
            prompt: 'Initial risk was $10.00. After costs, the trade lost $6.00. What is the R-multiple?',
            visual: {
              kind: 'table',
              rows: [
                { label: 'Initial risk', value: '$10.00' },
                { label: 'Net result', value: '−$6.00 (loss)' },
              ],
              caption: 'Journal summary for one simulated trade.',
            },
            unit: 'ratio',
            answer: -0.6,
            tolerance: 0.005,
            misconceptions: [
              { value: 0.6, misconception: 'r-sign', feedback: 'Check the sign: a loss gives a negative R.' },
              { value: -6, misconception: 'r-dollars', feedback: 'That’s the dollar result. Divide it by the $10.00 risk.' },
              { value: -1.67, tolerance: 0.01, misconception: 'r-inverted', feedback: 'You divided risk by result. R is result ÷ risk.' },
            ],
            wrongFeedback: 'R = net result ÷ initial risk = −$6.00 ÷ $10.00.',
            inputLabel: 'R-multiple (for example −0.5)',
            explanation: '−$6.00 ÷ $10.00 = −0.6R. The loss was smaller than planned, likely because it exited before the stop.',
          },
        },
        {
          kind: 'exercise',
          id: 'which-facts',
          exercise: {
            id: 'u9-journal-fields',
            kind: 'categorize',
            skills: ['journaling'],
            prompt: 'Sort each note: is it a useful journal fact, or not helpful for review?',
            categories: [
              { id: 'useful', label: 'Useful to record' },
              { id: 'not', label: 'Not helpful' },
            ],
            items: [
              { id: 'stop', text: 'Initial stop and why it was there', category: 'useful', feedback: 'The stop defines the risk; you need it to compute R.' },
              { id: 'costs', text: 'Fees and slippage on each fill', category: 'useful', feedback: 'Costs change the net result.' },
              { id: 'followed', text: 'Whether you followed the plan', category: 'useful', feedback: 'Plan adherence is the main thing to review.' },
              { id: 'mood', text: '“Should have bought more!” written after it went up', category: 'not', feedback: 'That’s hindsight, not a record of the decision.' },
              { id: 'screenshot', text: 'Only the final profit, with no plan', category: 'not', feedback: 'Without the plan, the result can’t be judged.' },
            ],
            explanation: 'Record the plan, costs and adherence. Hindsight wishes don’t help review.',
            rubricNote: 'Instructor-defined categories.',
          },
        },
      ],
      recap: ['Record plan, fills, costs and adherence.', 'R = net result ÷ initial risk, frozen at entry.'],
      glossary: ['journal', 'r-multiple', 'fee', 'slippage'],
      sources: [],
      review: { skills: ['journaling'] },
      help: {
        simpler: 'Write down what you planned before, and what happened after. R tells you how the result compares with what you were willing to lose.',
        example: 'Risk $8, won $16 after costs → +2R. Risk $8, lost $8 → −1R.',
      },
    },
    {
      id: 'u9-decision-outcome',
      version: 1,
      unitId: 'u9',
      kind: 'lesson',
      title: 'Good decision, bad outcome',
      objective: 'Judge a trade by the decision process, separately from its result.',
      minutes: 4,
      prerequisites: ['u9-journal'],
      contentType: 'scenario',
      steps: [
        {
          kind: 'concept',
          id: 'two-grades',
          title: 'Two separate questions',
          body:
            'Every trade gets two grades.\nDecision: did you follow a sound plan with sensible risk?\nOutcome: did it make or lose money?\n\nA sound plan can lose, and a reckless trade can win. Judging by outcome alone teaches you to repeat lucky mistakes and abandon sound plans.',
        },
        {
          kind: 'exercise',
          id: 'sort-trades',
          exercise: {
            id: 'u9-decision-grid',
            kind: 'categorize',
            skills: ['decision-vs-outcome'],
            prompt: 'Sort each trade by decision quality, ignoring the result.',
            categories: [
              { id: 'sound', label: 'Sound decision' },
              { id: 'poor', label: 'Poor decision' },
            ],
            items: [
              { id: 'a', text: 'Followed the plan, stop hit for −1R', category: 'sound', feedback: 'A planned loss within budget is a sound decision.' },
              { id: 'b', text: 'No stop, bought on a tip, gained +3R', category: 'poor', feedback: 'It won, but the process was unplanned and unprotected.' },
              { id: 'c', text: 'Followed the plan, target hit for +2R', category: 'sound', feedback: 'Sound process, good outcome.' },
              { id: 'd', text: 'Widened the stop, lost −2.5R', category: 'poor', feedback: 'Moving the stop broke the plan and grew the loss.' },
              { id: 'e', text: 'Passed on a setup that later rallied', category: 'sound', feedback: 'If the setup didn’t fit your plan, passing was sound, whatever happened next.' },
            ],
            explanation: 'Decision quality comes from the plan and risk, not the result.',
            rubricNote: 'Instructor-defined categories based on the course’s plan rules.',
          },
        },
        {
          kind: 'exercise',
          id: 'explain-loss',
          exercise: {
            id: 'u9-explain-loss',
            kind: 'decision',
            skills: ['decision-vs-outcome', 'journaling'],
            prompt: 'Choose the verdict and the best explanation.',
            situation: 'You bought at support with a stop at invalidation and risk within budget. The next quote gapped down and the stop filled $0.30 below its trigger, for −1.3R.',
            actions: [
              { id: 'sound', text: 'Sound decision, unlucky outcome' },
              { id: 'poor', text: 'Poor decision' },
            ],
            reasons: [
              { id: 'r1', text: 'The plan and size were right; the gap caused extra slippage, which stops can’t prevent.', points: 2, supports: ['sound'], feedback: 'Yes. You separated the process from a known risk of stop orders.' },
              { id: 'r2', text: 'It lost more than 1R, so the plan was bad.', points: 0, supports: ['poor'], misconception: 'outcome-bias', feedback: 'That judges by outcome. Gaps can push fills past the stop even with a sound plan.' },
              { id: 'r3', text: 'I should have known it would gap.', points: 0, supports: ['poor'], misconception: 'hindsight', feedback: 'That’s hindsight. The gap wasn’t knowable at entry.' },
              { id: 'r4', text: 'Sound, but next time I’ll skip stops because they slip.', points: 1, supports: ['sound'], misconception: 'skip-stops', feedback: 'The verdict is right, but removing stops would expose you to far larger losses.' },
            ],
            explanation: 'A loss beyond 1R from a gap is a cost of stop orders, not proof the decision was wrong.',
            rubricNote: REASONING,
          },
        },
      ],
      recap: ['Grade the decision and the outcome separately.', 'Sound plans can lose; reckless trades can win.'],
      glossary: ['r-multiple', 'gap', 'hindsight-bias'],
      sources: ['finra-stop-orders'],
      review: { skills: ['decision-vs-outcome'] },
      help: {
        simpler: 'Wearing a seatbelt is a good choice even on trips with no accident. Judge the choice, not the luck.',
        example: 'You followed the plan and lost 1R: good decision. You bought a tip without a stop and won: poor decision, lucky outcome.',
      },
    },
    {
      id: 'u9-stats',
      version: 1,
      unitId: 'u9',
      kind: 'lesson',
      title: 'Win rate, averages and sample size',
      objective: 'Calculate win rate and average R, and explain why small samples say little.',
      minutes: 4,
      prerequisites: ['u9-decision-outcome'],
      contentType: 'scenario',
      steps: [
        {
          kind: 'concept',
          id: 'stats',
          title: 'Reading your numbers',
          body:
            '[[win-rate]] is winners ÷ total trades. It says nothing about size: a 40% win rate can be fine if wins are bigger than losses.\n\n[[average-win]] and [[average-loss]] (in R) complete the picture.\n\n[[sample-size]] matters most. Ten trades can look great or terrible by chance. Treat small samples as a rough hint, not proof.',
        },
        {
          kind: 'exercise',
          id: 'win-rate',
          exercise: {
            id: 'u9-win-rate',
            kind: 'numeric',
            skills: ['trading-stats'],
            prompt: 'Your journal shows 8 closed trades: 3 winners and 5 losers. What is the win rate in percent?',
            unit: 'number',
            answer: 37.5,
            tolerance: 0.1,
            misconceptions: [
              { value: 60, misconception: 'win-loss-ratio', feedback: 'That’s winners ÷ losers. Win rate is winners ÷ all trades.' },
              { value: 3, misconception: 'count-not-rate', feedback: 'That’s the number of winners. Divide by all 8 trades.' },
              { value: 62.5, misconception: 'loss-rate', feedback: 'That’s the share of losers.' },
            ],
            wrongFeedback: 'Win rate = winners ÷ total trades × 100.',
            inputLabel: 'Win rate (%)',
            explanation: '3 ÷ 8 = 0.375, or 37.5%. With only 8 trades, this could easily change a lot.',
          },
        },
        {
          kind: 'exercise',
          id: 'small-sample',
          exercise: {
            id: 'u9-small-sample',
            kind: 'choice',
            skills: ['trading-stats'],
            prompt: 'After 6 simulated trades, your win rate is 83%. What’s the most accurate conclusion?',
            visual: {
              kind: 'table',
              rows: [
                { label: 'Trades', value: '6' },
                { label: 'Winners', value: '5' },
                { label: 'Average R', value: '+0.9R' },
              ],
              caption: 'Statistics from six practice trades.',
            },
            options: [
              { id: 'a', text: 'It’s an encouraging start, but 6 trades is far too few to know if the method works.', correct: true, feedback: 'Yes. Small samples swing a lot by chance.' },
              { id: 'b', text: 'The method works; it’s time to increase size.', misconception: 'small-sample', feedback: 'Six results can’t tell skill from luck.' },
              { id: 'c', text: 'An 83% win rate guarantees future profits.', misconception: 'guarantee', feedback: 'Nothing guarantees future results, especially from a small sample.' },
            ],
            explanation: 'Always read statistics together with the sample size.',
          },
        },
        {
          kind: 'exercise',
          id: 'average',
          exercise: {
            id: 'u9-average-r',
            kind: 'numeric',
            skills: ['trading-stats'],
            prompt: 'Four trades returned +2R, −1R, −1R and +1R. What is the average R per trade?',
            unit: 'ratio',
            answer: 0.25,
            tolerance: 0.005,
            misconceptions: [
              { value: 1, misconception: 'sum-not-average', feedback: 'That’s the total. Divide by the 4 trades.' },
              { value: 1.5, misconception: 'winners-only', feedback: 'That’s the average win only. Include the losers.' },
            ],
            wrongFeedback: 'Add the four results and divide by 4.',
            inputLabel: 'Average R',
            explanation: '(2 − 1 − 1 + 1) ÷ 4 = 1 ÷ 4 = +0.25R per trade. Half the trades lost, yet the average is positive because the win was larger.',
          },
        },
      ],
      recap: ['Win rate = winners ÷ all trades.', 'Average R includes wins and losses.', 'Small samples are hints, not proof.'],
      glossary: ['win-rate', 'average-win', 'average-loss', 'sample-size', 'r-multiple'],
      sources: [],
      review: { skills: ['trading-stats'] },
      help: {
        simpler: 'Flip a coin 6 times and you might get 5 heads. That doesn’t make the coin special. Trading results work the same way.',
        example: '10 trades: 4 wins of +2R, 6 losses of −1R. Win rate 40%, total +2R, average +0.2R.',
      },
    },
    {
      id: 'u9-checkpoint',
      version: 1,
      unitId: 'u9',
      kind: 'checkpoint',
      title: 'Unit 9 checkpoint',
      objective: 'Calculate and interpret journal results in new examples.',
      minutes: 3,
      prerequisites: ['u9-stats'],
      contentType: 'scenario',
      steps: [
        { kind: 'concept', id: 'intro', title: 'Review like a coach', body: 'New numbers and new trades. Compute, then judge the process separately from the result.' },
        {
          kind: 'exercise',
          id: 'cp-r',
          exercise: {
            id: 'u9-cp-r-win',
            kind: 'numeric',
            skills: ['journaling'],
            prompt: 'You bought 15 shares with an initial risk of $12.00. After fees and slippage, the trade made $18.00. What is the R-multiple?',
            unit: 'ratio',
            answer: 1.5,
            tolerance: 0.005,
            misconceptions: [
              { value: 0.67, tolerance: 0.01, misconception: 'r-inverted', feedback: 'You divided risk by result. R is result ÷ risk.' },
              { value: 18, misconception: 'r-dollars', feedback: 'That’s the dollar result. Divide by the $12.00 risk.' },
            ],
            wrongFeedback: 'R = net result ÷ initial risk.',
            inputLabel: 'R-multiple',
            explanation: '$18.00 ÷ $12.00 = +1.5R.',
          },
        },
        {
          kind: 'exercise',
          id: 'cp-outcome',
          exercise: {
            id: 'u9-cp-lucky-win',
            kind: 'choice',
            skills: ['decision-vs-outcome'],
            prompt: 'You bought without a stop because a video said the price “can’t go lower”. It rose and you made +$25. How should the journal rate it?',
            options: [
              { id: 'a', text: 'Poor decision, good outcome: no plan and no stop.', correct: true, feedback: 'Yes. The profit doesn’t make the process sound.' },
              { id: 'b', text: 'Sound decision, because it made money.', misconception: 'outcome-bias', feedback: 'That’s judging by outcome.' },
              { id: 'c', text: 'Can’t be rated without knowing the next day’s price.', misconception: 'future-grading', feedback: 'Decisions are graded on what was known at the time, not later prices.' },
            ],
            explanation: 'Rate the process first. An unprotected trade on a tip is poor, even when it wins.',
          },
        },
        {
          kind: 'exercise',
          id: 'cp-stats',
          exercise: {
            id: 'u9-cp-compare',
            kind: 'choice',
            skills: ['trading-stats'],
            prompt: 'Plan A: 45 trades, 40% win rate, average +0.3R. Plan B: 5 trades, 80% win rate, average +0.8R. Which statement is most justified?',
            options: [
              { id: 'a', text: 'Plan A has more evidence behind it; Plan B needs many more trades before comparing.', correct: true, feedback: 'Yes. Sample size decides how much a statistic can tell you.' },
              { id: 'b', text: 'Plan B is clearly better.', misconception: 'small-sample', feedback: 'Five trades are too few to compare with 45.' },
              { id: 'c', text: 'Plan A is losing because it wins less than half the time.', misconception: 'win-rate-only', feedback: 'Its average R is positive, so wins are larger than losses on average.' },
            ],
            explanation: 'Compare statistics only with their sample sizes in view. Even 45 trades is a modest sample.',
            rubricNote: 'Instructor-defined judgment about evidence, not a statistical test.',
          },
        },
      ],
      recap: ['You computed R, rated a lucky win as a poor decision, and weighed sample sizes.'],
      glossary: ['r-multiple', 'sample-size', 'win-rate'],
      sources: [],
      review: { skills: ['journaling', 'decision-vs-outcome', 'trading-stats'] },
      help: { simpler: 'R compares result with risk. Judge process before result. More trades means more trustworthy numbers.', example: 'Risk $12, made $18 → +1.5R.' },
    },
  ],
};
