import type { Unit } from '../schema';
import { bars, d } from '../helpers';

export const unit02: Unit = {
  id: 'u2',
  number: 2,
  title: 'How orders work',
  summary: 'Bid, ask and spread; market, limit and stop orders; and why fills surprise people.',
  lessons: [
    {
      id: 'u2-bid-ask',
      version: 1,
      unitId: 'u2',
      kind: 'lesson',
      title: 'Bid, ask and spread',
      objective: 'Predict which price an immediate buy or sell uses, and what the spread costs.',
      minutes: 3,
      prerequisites: ['u1-checkpoint'],
      contentType: 'factual',
      steps: [
        {
          kind: 'concept',
          id: 'two-prices',
          title: 'A quote has two prices',
          body:
            'The [[bid]] is the highest price a buyer is offering right now. The [[ask]] is the lowest price a seller will accept. The gap between them is the [[spread]].\n\nAn immediate buy usually pays about the ask. An immediate sell usually receives about the bid.',
          visual: { kind: 'quote', bid: d(9.99), ask: d(10.03), last: d(10.01), caption: 'Spread: $10.03 − $9.99 = $0.04' },
        },
        {
          kind: 'exercise',
          id: 'round-trip',
          exercise: {
            id: 'u2-round-trip-cost',
            kind: 'numeric',
            skills: ['spread'],
            prompt: 'The bid is $24.95 and the ask is $25.05. You buy 10 shares immediately, then sell all 10 immediately. The quote does not change. Before fees, how much did you lose?',
            visual: { kind: 'quote', bid: d(24.95), ask: d(25.05), caption: 'Quote stays the same' },
            unit: 'usd',
            answer: d(1),
            tolerance: 0,
            inputLabel: 'Loss in dollars (as a positive number)',
            misconceptions: [
              { value: d(0.1), misconception: 'spread-one-share', feedback: '$0.10 is the spread on one share. You traded 10 shares.' },
              { value: d(0.5), misconception: 'half-spread', feedback: 'You pay the full spread on a round trip: buy at the ask, sell at the bid.' },
              { value: 0, misconception: 'no-move-no-cost', feedback: 'The price did not move, but you bought at $25.05 and sold at $24.95.' },
            ],
            wrongFeedback: 'You buy at the ask and sell at the bid. Multiply the spread by the number of shares.',
            explanation: 'Buy 10 × $25.05 = $250.50. Sell 10 × $24.95 = $249.50. Lost: $1.00, the spread × 10 shares.',
          },
        },
        {
          kind: 'concept',
          id: 'last-price',
          title: 'The last price is history',
          body:
            'The [[last-price]] is the most recent trade. It is not a promise about your trade. Investor.gov puts it plainly: the last-traded price is not necessarily the price at which a market order will be executed.\n\nWide spreads make each round trip more expensive, and that adds up when you trade often.',
        },
        {
          kind: 'exercise',
          id: 'which-price',
          exercise: {
            id: 'u2-which-price',
            kind: 'choice',
            skills: ['spread'],
            prompt: 'Last trade $8.00, bid $7.90, ask $8.10. You place a buy that fills immediately. About what price should you expect?',
            visual: { kind: 'quote', bid: d(7.9), ask: d(8.1), last: d(8), caption: 'Current quote' },
            options: [
              { id: 'ask', text: 'About $8.10, the ask', correct: true, feedback: 'Yes. An immediate buy takes the seller’s price.' },
              { id: 'last', text: '$8.00, the last trade', misconception: 'last-price-fill', feedback: 'The last price already happened. Your buy needs a seller now, at the ask.' },
              { id: 'bid', text: '$7.90, the bid', misconception: 'bid-ask-swap', feedback: 'The bid is what buyers offer. You would receive about that when selling.' },
              { id: 'mid', text: '$8.00, halfway between', misconception: 'mid-fill', feedback: 'An immediate buy does not split the spread for you. Expect the ask.' },
            ],
            explanation: 'Buys execute at or near the ask, sells at or near the bid.',
          },
        },
      ],
      recap: ['Buy near the ask, sell near the bid.', 'A round trip costs about the spread × shares, before fees.', 'The last price is not your price.'],
      glossary: ['bid', 'ask', 'spread', 'last-price'],
      sources: ['sec-bid-price', 'sec-order-types'],
      review: { skills: ['spread'] },
      help: {
        simpler: 'It is like a currency exchange booth: they buy from you at one price and sell to you at a slightly higher one. The difference is the spread.',
        example: 'Bid $50.00, ask $50.04. Buy 25 shares and sell right away: you lose 25 × $0.04 = $1.00 before fees.',
      },
    },
    {
      id: 'u2-market-limit',
      version: 1,
      unitId: 'u2',
      kind: 'lesson',
      title: 'Market and limit orders',
      objective: 'Choose between certainty of a fill and control of the price.',
      minutes: 4,
      prerequisites: ['u2-bid-ask'],
      contentType: 'factual',
      steps: [
        {
          kind: 'concept',
          id: 'two-orders',
          title: 'Speed or price control',
          body:
            'A [[market-order]] trades right away at the best available price. It usually fills, but the price is not guaranteed.\n\nA [[limit-order]] sets your worst acceptable price. A buy limit fills only at your price or lower; a sell limit only at your price or higher. It protects the price, but it may never fill.',
        },
        {
          kind: 'exercise',
          id: 'lab-limit',
          exercise: {
            id: 'u2-lab-buy-limit',
            kind: 'order-sim',
            skills: ['market-vs-limit'],
            prompt: 'Choose an order type and price, then watch what happens as new quotes arrive.',
            goal: 'Buy 5 shares, paying no more than $20.00 per share.',
            side: 'buy',
            quantity: 5,
            quotes: [
              { bid: d(19.98), ask: d(20.02) },
              { bid: d(20.04), ask: d(20.08) },
              { bid: d(20.01), ask: d(20.05) },
              { bid: d(19.96), ask: d(20) },
              { bid: d(19.94), ask: d(19.98) },
              { bid: d(19.97), ask: d(20.01) },
            ],
            allowed: ['market', 'limit'],
            startPrice: d(20.1),
            priceStep: 1,
            rubric: { type: 'fill-at-or-better', price: d(20), failFeedback: 'The goal needs the shares bought at $20.00 or less. A buy limit at or a little below $20.00 does that.' },
            explanation: 'A buy limit at $20.00 waits until the ask is $20.00 or lower, then fills there or better. A market order fills at the next ask, which here was $20.08.',
            rubricNote: 'Graded by running your order through this fixed quote sequence.',
          },
        },
        {
          kind: 'exercise',
          id: 'tradeoff',
          exercise: {
            id: 'u2-limit-tradeoff',
            kind: 'choice',
            skills: ['market-vs-limit'],
            prompt: 'What is the trade-off of a buy limit order placed below the current ask?',
            options: [
              { id: 'a', text: 'You control the price, but you might not buy at all.', correct: true, feedback: 'Exactly. If the ask never reaches your limit, nothing happens.' },
              { id: 'b', text: 'It guarantees a fill at exactly your price.', misconception: 'limit-guarantees-fill', feedback: 'A limit guarantees the price if it fills, not that it fills.' },
              { id: 'c', text: 'It fills faster than a market order.', misconception: 'limit-faster', feedback: 'Usually the opposite: a market order takes the available price now.' },
              { id: 'd', text: 'It fills at the last traded price.', misconception: 'last-price-fill', feedback: 'Fills depend on the ask reaching your limit, not the last trade.' },
            ],
            explanation: 'Limit orders trade certainty of execution for control of price. Market orders do the reverse.',
          },
        },
      ],
      recap: ['Market: likely fill, uncertain price.', 'Limit: price control, possible no fill.', 'A buy limit fills at your price or lower.'],
      glossary: ['market-order', 'limit-order', 'ask'],
      sources: ['sec-order-types', 'finra-order-types'],
      review: { skills: ['market-vs-limit'] },
      help: {
        simpler: 'A market order says “sell me one now, whatever it costs.” A limit order says “I’ll buy only if it’s $20 or less.”',
        example: 'Ask is $10.10. A buy limit at $10.00 waits. If the ask drops to $9.98, it fills at $9.98. If it never drops, you never buy.',
      },
    },
    {
      id: 'u2-stops',
      version: 1,
      unitId: 'u2',
      kind: 'lesson',
      title: 'Stop orders, gaps and surprises',
      objective: 'Predict how a protective stop fills, including when price gaps past it.',
      minutes: 4,
      prerequisites: ['u2-market-limit'],
      contentType: 'factual',
      steps: [
        {
          kind: 'concept',
          id: 'stop-basics',
          title: 'A stop waits, then becomes a market order',
          body:
            'A [[stop-order]] waits for a trigger price. When price reaches it, it becomes a market order. A sell stop below your purchase price is often used to limit a loss.\n\nBecause it becomes a market order, FINRA notes the fill can be significantly different from the stop price when prices move fast.',
        },
        {
          kind: 'concept',
          id: 'gaps',
          title: 'When price jumps',
          body:
            'A [[gap]] is a jump with no trading in between, often at a new session after news. If a stock closes near $50 and next opens at $46, a sell stop at $49 triggers at the open and fills near $46, not $49.',
          visual: {
            kind: 'candles',
            candles: bars([
              [50.4, 50.7, 50.1, 50.5],
              [50.5, 50.8, 50.2, 50.3],
              [50.3, 50.6, 49.9, 50.1],
              [50.1, 50.4, 49.8, 50.05],
              [46.2, 46.6, 45.7, 46.1],
              [46.1, 46.5, 45.9, 46.3],
            ]),
            levels: [{ price: d(49), label: 'Stop $49.00' }],
            caption: 'Price gaps from about $50 to about $46 between sessions',
          },
        },
        {
          kind: 'exercise',
          id: 'lab-stop',
          exercise: {
            id: 'u2-lab-sell-stop',
            kind: 'order-sim',
            skills: ['stop-orders'],
            prompt: 'Set up the order your plan describes, then step through the quotes.',
            goal: 'You own 10 shares. Plan: sell automatically only if the bid falls to $49.00.',
            side: 'sell',
            quantity: 10,
            quotes: [
              { bid: d(50.1), ask: d(50.14) },
              { bid: d(50.05), ask: d(50.09) },
              { bid: d(50.02), ask: d(50.06) },
              { bid: d(46), ask: d(46.06) },
              { bid: d(46.2), ask: d(46.26) },
            ],
            allowed: ['market', 'limit', 'stop'],
            startPrice: d(50),
            priceStep: 5,
            rubric: { type: 'exit-triggered-by', price: d(49), failFeedback: 'The plan asks for an automatic sale only if price falls to $49.00. That is a sell stop at $49.00.' },
            explanation: 'A sell stop at $49.00 waits while the bid is above it. When the next session opened at $46.00, the stop triggered and filled at $46.00 — $3.00 per share worse than the stop price.',
            rubricNote: 'Graded on whether the order matches the written plan. The gap shows why a stop is not a guaranteed exit price.',
          },
        },
        {
          kind: 'exercise',
          id: 'gap-loss',
          exercise: {
            id: 'u2-gap-loss',
            kind: 'numeric',
            skills: ['stop-orders'],
            prompt: 'You bought 20 shares at $30.00 with a sell stop at $29.00. After overnight news, the next bid is $27.50 and the stop fills there. Before fees, what is the loss?',
            unit: 'usd',
            answer: d(50),
            tolerance: 0,
            inputLabel: 'Loss in dollars (as a positive number)',
            misconceptions: [
              { value: d(20), misconception: 'stop-is-guarantee', feedback: '$20 is the planned loss to $29.00. The fill happened at $27.50 because of the gap.' },
              { value: d(2.5), misconception: 'per-share', feedback: '$2.50 is the loss per share. You held 20 shares.' },
              { value: d(30), misconception: 'gap-only', feedback: '$30 is only the part below the stop. Measure from your $30.00 entry.' },
            ],
            wrongFeedback: 'Loss = shares × (entry − fill price) = 20 × ($30.00 − $27.50).',
            explanation: '20 × $2.50 = $50, more than double the $20 planned. A stop is a trigger, not a floor.',
          },
        },
      ],
      recap: ['A stop becomes a market order when triggered.', 'In a gap, the fill can be far past the stop price.', 'Planned risk is an estimate, not a maximum.'],
      glossary: ['stop-order', 'gap', 'market-order'],
      sources: ['finra-stop-orders', 'finra-order-types', 'sec-order-types'],
      review: { skills: ['stop-orders'] },
      help: {
        simpler: 'A stop is like a smoke alarm that calls for help: it goes off at a set point, but help arrives at whatever price is available, not the price you wished for.',
        example: 'Stop at $15.00. Price drifts from $15.20 to $15.00: fills near $15.00. Price jumps from $15.20 to $14.10 overnight: fills near $14.10.',
      },
    },
    {
      id: 'u2-checkpoint',
      version: 1,
      unitId: 'u2',
      kind: 'checkpoint',
      title: 'Unit 2 checkpoint',
      objective: 'Apply order mechanics to new situations.',
      minutes: 3,
      prerequisites: ['u2-stops'],
      contentType: 'factual',
      steps: [
        { kind: 'concept', id: 'intro', title: 'Orders in new situations', body: 'Three new situations. Think about which side of the quote you trade against and what each order type promises.' },
        {
          kind: 'exercise',
          id: 'cp-spread',
          exercise: {
            id: 'u2-cp-spread',
            kind: 'numeric',
            skills: ['spread'],
            prompt: 'Bid $49.80, ask $50.00. You buy 30 shares immediately and sell them immediately with no quote change. Before fees, what does the round trip cost?',
            unit: 'usd',
            answer: d(6),
            tolerance: 0,
            inputLabel: 'Cost in dollars',
            misconceptions: [
              { value: d(0.2), misconception: 'spread-one-share', feedback: 'That is the spread per share. Multiply by 30.' },
              { value: d(3), misconception: 'half-spread', feedback: 'You pay the whole spread on a round trip, not half.' },
            ],
            wrongFeedback: 'Spread × shares = $0.20 × 30.',
            explanation: '30 × $0.20 = $6.00.',
          },
        },
        {
          kind: 'exercise',
          id: 'cp-market',
          exercise: {
            id: 'u2-cp-must-exit',
            kind: 'choice',
            skills: ['market-vs-limit'],
            prompt: 'You must sell your practice shares now, and getting out matters more than the exact price. Which order fits?',
            options: [
              { id: 'm', text: 'A market sell order', correct: true, feedback: 'Yes. It prioritizes getting filled, at roughly the bid.' },
              { id: 'l', text: 'A sell limit well above the current bid', misconception: 'limit-guarantees-fill', feedback: 'That waits for a higher price and may not fill at all.' },
              { id: 's', text: 'A sell stop below the current price', misconception: 'stop-immediate', feedback: 'A sell stop waits for price to fall to it. It will not sell now.' },
            ],
            explanation: 'When certainty of a fill matters most, a market order fits; the price is what the market offers.',
          },
        },
        {
          kind: 'exercise',
          id: 'cp-gap',
          exercise: {
            id: 'u2-cp-gap-stop',
            kind: 'choice',
            skills: ['stop-orders'],
            prompt: 'You hold shares with a sell stop at $19.00. The price closes at $20.00, then the next session opens at $17.00. What most likely happens?',
            options: [
              { id: 'a', text: 'The stop triggers at the open and fills near $17.00.', correct: true, feedback: 'Right. The stop becomes a market order at the first available price.' },
              { id: 'b', text: 'It fills at exactly $19.00.', misconception: 'stop-is-guarantee', feedback: 'There was no trading at $19.00 to fill against. The stop is a trigger, not a guaranteed price.' },
              { id: 'c', text: 'It does nothing because $19.00 was skipped.', misconception: 'stop-skipped', feedback: 'A sell stop triggers when price is at or below its level, so a gap below it still triggers it.' },
            ],
            explanation: 'Gaps can push stop fills well beyond the stop price.',
          },
        },
      ],
      recap: ['You priced a round trip, chose an order for certainty, and predicted a gapped stop.'],
      glossary: ['spread', 'market-order', 'stop-order', 'gap'],
      sources: ['sec-order-types', 'finra-stop-orders'],
      review: { skills: ['spread', 'market-vs-limit', 'stop-orders'] },
      help: { simpler: 'Buy at the ask, sell at the bid. Market = now. Limit = at my price or better. Stop = wait, then go at market.', example: 'A sell stop at $9 with price gapping from $10 to $8 fills near $8.' },
    },
  ],
};
