import type { Unit } from '../schema';
import { d } from '../helpers';

export const unit01: Unit = {
  id: 'u1',
  number: 1,
  title: 'What you are buying',
  summary: 'Shares, value, gains, and the difference between trading and investing.',
  lessons: [
    {
      id: 'u1-shares',
      version: 1,
      unitId: 'u1',
      kind: 'lesson',
      title: 'Shares and what they are worth',
      objective: 'Work out what a position is worth and separate its value from its gain.',
      minutes: 3,
      prerequisites: [],
      contentType: 'factual',
      steps: [
        {
          kind: 'concept',
          id: 'buy-two',
          title: 'You buy 2 practice shares at $10 each',
          body:
            'A [[share]] is a small slice of ownership in a company. You buy 2 practice shares of a fictional company at $10 each.\n\nYou paid 2 × $10 = $20. That $20 is your [[cost-basis]]: what the position cost you.',
          visual: { kind: 'shares', shares: 2, price: d(10), caption: '2 shares × $10.00 = $20.00 paid' },
        },
        {
          kind: 'exercise',
          id: 'value-at-12',
          exercise: {
            id: 'u1-value-at-12',
            kind: 'numeric',
            skills: ['position-value'],
            prompt: 'The practice price moves from $10 to $12. What are your 2 shares worth now?',
            visual: { kind: 'shares', shares: 2, price: d(12), basis: d(10), caption: 'Price is now $12.00 per share' },
            unit: 'usd',
            answer: d(24),
            tolerance: 0,
            inputLabel: 'Value of your 2 shares, in dollars',
            misconceptions: [
              { value: d(4), misconception: 'value-vs-gain', feedback: '$4 is how much the value went up — the gain. The value is shares × current price: 2 × $12.' },
              { value: d(12), misconception: 'one-share', feedback: '$12 is the price of one share. You own two, so multiply by 2.' },
              { value: d(20), misconception: 'cost-not-value', feedback: '$20 is what you paid. Value uses today’s price, $12, not the price you paid.' },
            ],
            wrongFeedback: 'Value is shares × current price. Try 2 × $12.',
            explanation: 'Position value = number of shares × current price = 2 × $12 = $24.',
          },
        },
        {
          kind: 'concept',
          id: 'value-vs-gain',
          title: 'Value is not the same as gain',
          body:
            'Your shares are worth $24, and you paid $20. The $4 difference is an [[unrealized-gain]]. It exists only on screen until you sell, and the price can move again first.\n\nReal trading also has costs, such as a [[fee]] and the [[spread]], that shrink a gain.',
          more: 'Selling turns an unrealized result into a realized one. Even then, costs are subtracted from what you keep.',
        },
        {
          kind: 'exercise',
          id: 'unrealized',
          exercise: {
            id: 'u1-unrealized-statement',
            kind: 'choice',
            skills: ['profit-loss'],
            prompt: 'The price is still $12 and you have not sold. Which statement is accurate?',
            options: [
              { id: 'a', text: 'I have a $4 unrealized gain, and it can still change.', correct: true, feedback: 'Right. It is a gain on screen that is not locked in yet.' },
              { id: 'b', text: 'I made $4 of profit that I get to keep.', misconception: 'unrealized-is-realized', feedback: 'Not yet. Profit is only locked in when you sell, and costs reduce it. Until then the price can fall back.' },
              { id: 'c', text: 'My shares are worth $4.', misconception: 'value-vs-gain', feedback: '$4 is the gain. The shares are worth $24 in total.' },
              { id: 'd', text: 'Nothing has changed because I have not sold.', misconception: 'nothing-changed', feedback: 'Something did change: the value of your position went up. It just is not locked in.' },
            ],
            explanation: 'Unrealized gain = current value − cost = $24 − $20 = $4. It becomes realized only when you sell.',
          },
        },
      ],
      recap: [
        'Value = shares × current price.',
        'Gain = value − what you paid. Until you sell, it is unrealized and can change.',
        'Real trades have costs that shrink gains.',
      ],
      glossary: ['share', 'cost-basis', 'unrealized-gain', 'fee', 'spread'],
      sources: ['sec-stocks'],
      review: { skills: ['position-value', 'profit-loss'] },
      help: {
        simpler: 'Think of trading cards. You bought 2 cards for $10 each. If each card is now worth $12, your pile is worth $24. You are $4 ahead on paper, but you only really have that $4 if you sell.',
        example: 'You buy 5 shares at $8 ($40 total). The price becomes $9. Value: 5 × $9 = $45. Unrealized gain: $45 − $40 = $5.',
      },
    },
    {
      id: 'u1-buy-sell',
      version: 1,
      unitId: 'u1',
      kind: 'lesson',
      title: 'Buying, selling and profit or loss',
      objective: 'Calculate a realized result after costs, and value a position that has fallen.',
      minutes: 3,
      prerequisites: ['u1-shares'],
      contentType: 'factual',
      steps: [
        {
          kind: 'concept',
          id: 'realize',
          title: 'Selling locks in the result',
          body:
            'When you sell, the result becomes a [[realized-gain]] or loss. Realized result = what you received − what you paid − costs.\n\nExample: buy 4 shares at $15 ($60), sell at $17 ($68), pay a $1 fee each time. Result: $68 − $60 − $2 = $6.',
          visual: { kind: 'table', rows: [{ label: 'Received', value: '$68.00' }, { label: 'Paid', value: '−$60.00' }, { label: 'Fees', value: '−$2.00' }, { label: 'Realized', value: '+$6.00' }], caption: 'Realized result after fees' },
        },
        {
          kind: 'exercise',
          id: 'realized-calc',
          exercise: {
            id: 'u1-realized-with-fees',
            kind: 'numeric',
            skills: ['profit-loss'],
            prompt: 'You buy 10 shares at $6.00 and later sell all 10 at $6.50. Each trade costs a $0.50 fee. What is your realized result?',
            unit: 'usd',
            answer: d(4),
            tolerance: 0,
            inputLabel: 'Realized result in dollars (use a minus sign for a loss)',
            misconceptions: [
              { value: d(5), misconception: 'ignore-fees', feedback: '$5 is the result before fees. You paid a $0.50 fee twice: once to buy and once to sell.' },
              { value: d(4.5), misconception: 'one-fee', feedback: 'Close. Fees apply to both the buy and the sell, so subtract $1.00 in total.' },
              { value: d(0.5), misconception: 'per-share', feedback: '$0.50 is the gain per share before fees. You had 10 shares.' },
            ],
            wrongFeedback: 'Received − paid − fees: (10 × $6.50) − (10 × $6.00) − (2 × $0.50).',
            explanation: 'Received $65.00, paid $60.00, fees $1.00. Realized result = $65 − $60 − $1 = $4.',
          },
        },
        {
          kind: 'concept',
          id: 'losses',
          title: 'Prices fall too',
          body:
            'Stock prices move down as well as up, and you can lose money you put in. If you buy 3 shares at $20 ($60) and the price drops to $17, the position is worth 3 × $17 = $51, an unrealized loss of $9.',
          visual: { kind: 'shares', shares: 3, price: d(17), basis: d(20), caption: '3 shares, now $17.00 each' },
        },
        {
          kind: 'exercise',
          id: 'value-falls',
          exercise: {
            id: 'u1-value-after-drop',
            kind: 'numeric',
            skills: ['position-value'],
            prompt: 'You hold 8 shares bought at $25. The price is now $22.50. What is the position worth now?',
            unit: 'usd',
            answer: d(180),
            tolerance: 0,
            inputLabel: 'Position value in dollars',
            misconceptions: [
              { value: d(-20), misconception: 'value-vs-gain', feedback: '−$20 is the unrealized loss. The question asks what the shares are worth: 8 × $22.50.' },
              { value: d(20), misconception: 'value-vs-gain', feedback: '$20 is the size of the loss. Value is 8 × $22.50.' },
              { value: d(200), misconception: 'cost-not-value', feedback: '$200 is what you paid. Value uses the current price.' },
            ],
            wrongFeedback: 'Value = shares × current price = 8 × $22.50.',
            explanation: '8 × $22.50 = $180. You paid $200, so the unrealized loss is $20.',
          },
        },
      ],
      recap: ['Realized result = received − paid − all costs.', 'Fees apply on both the buy and the sell.', 'Value can drop below what you paid.'],
      glossary: ['realized-gain', 'fee', 'cost-basis'],
      sources: ['sec-stocks'],
      review: { skills: ['profit-loss', 'position-value'] },
      help: {
        simpler: 'Count the money that came in, subtract the money that went out, and remember that fees are money going out too.',
        example: 'Buy 2 shares at $50 ($100). Sell at $49 ($98). Two $1 fees. Result: $98 − $100 − $2 = −$4.',
      },
    },
    {
      id: 'u1-trade-invest',
      version: 1,
      unitId: 'u1',
      kind: 'lesson',
      title: 'Trading, investing and diversification',
      objective: 'Tell short-term trading from long-term investing, and explain diversification as a separate idea.',
      minutes: 4,
      prerequisites: ['u1-buy-sell'],
      contentType: 'factual',
      steps: [
        {
          kind: 'concept',
          id: 'two-approaches',
          title: 'Two different activities',
          body:
            '[[investing]] usually means holding for years toward a goal. [[trading]] means buying and selling more often to try to profit from shorter moves.\n\nFINRA notes that short-term trading is generally less reliable than long-term investing, and frequent trading adds costs. This app teaches trading mechanics with virtual money so you can see those risks safely.',
        },
        {
          kind: 'exercise',
          id: 'sort-approach',
          exercise: {
            id: 'u1-sort-trading-investing',
            kind: 'categorize',
            skills: ['investing-vs-trading'],
            prompt: 'Sort each description.',
            categories: [
              { id: 'investing', label: 'More like investing' },
              { id: 'trading', label: 'More like trading' },
            ],
            items: [
              { id: 'retire', text: 'Buying shares to hold for 20 years toward retirement', category: 'investing', feedback: 'A long holding period toward a goal is investing.' },
              { id: 'intraday', text: 'Buying at 10:00 and selling at 11:30 the same day', category: 'trading', feedback: 'Holding for minutes or hours to catch a short move is trading.' },
              { id: 'weekly', text: 'Opening and closing several positions each week', category: 'trading', feedback: 'Frequent buying and selling is trading, and the costs add up.' },
              { id: 'monthly', text: 'Adding money to a broad fund every month and rarely selling', category: 'investing', feedback: 'Regular long-term buying with little selling is investing.' },
            ],
            explanation: 'The difference is mostly time horizon and how often you buy and sell.',
          },
        },
        {
          kind: 'concept',
          id: 'diversify',
          title: 'Diversification is a separate idea',
          body:
            '[[diversification]] means spreading money across different investments so one bad result hurts less: “don’t put all your eggs in one basket.”\n\nIt reduces some risks but does not remove them. This simulator holds one position at a time on purpose, so it is not a model of a diversified portfolio.',
        },
        {
          kind: 'exercise',
          id: 'diversify-check',
          exercise: {
            id: 'u1-diversification-choice',
            kind: 'choice',
            skills: ['diversification'],
            prompt: 'Which choice is the most diversified?',
            options: [
              { id: 'a', text: 'Owning shares in several companies across different industries', correct: true, feedback: 'Yes. Problems in one company or industry affect only part of the money.' },
              { id: 'b', text: 'Owning many shares of one company', misconception: 'many-shares-diversified', feedback: 'More shares of one company is still one company. If it struggles, everything is affected.' },
              { id: 'c', text: 'Owning three companies that all make the same product', misconception: 'same-sector', feedback: 'Better than one, but they share the same risks. Spreading across industries diversifies more.' },
              { id: 'd', text: 'Trading one stock many times', misconception: 'trading-diversifies', feedback: 'Trading often is about timing, not diversification. It is still exposure to one company.' },
            ],
            explanation: 'Diversification spreads money across different investments and industries so a problem in one area hurts less.',
          },
        },
      ],
      recap: ['Investing: long horizon. Trading: shorter moves, more costs.', 'Diversification spreads risk across different investments.', 'Neither removes the possibility of loss.'],
      glossary: ['investing', 'trading', 'diversification'],
      sources: ['finra-frequent-trading', 'sec-diversification', 'sec-stocks'],
      review: { skills: ['investing-vs-trading', 'diversification'] },
      help: {
        simpler: 'Investing is planting a tree and waiting years. Trading is trying to catch short moves, many times. Diversifying is planting different kinds of trees so one disease doesn’t wipe out the whole garden.',
        example: 'Someone who holds a mix of companies for 15 years is investing and diversified. Someone who buys and sells one stock every day is trading and not diversified.',
      },
    },
    {
      id: 'u1-checkpoint',
      version: 1,
      unitId: 'u1',
      kind: 'checkpoint',
      title: 'Unit 1 checkpoint',
      objective: 'Show you can apply Unit 1 ideas to new numbers.',
      minutes: 3,
      prerequisites: ['u1-trade-invest'],
      contentType: 'factual',
      steps: [
        {
          kind: 'concept',
          id: 'intro',
          title: 'New examples, same ideas',
          body: 'These questions use different numbers from the lessons. Getting them right on the first try is how the app decides a skill is demonstrated, not just clicked through.',
        },
        {
          kind: 'exercise',
          id: 'cp-value',
          exercise: {
            id: 'u1-cp-value',
            kind: 'numeric',
            skills: ['position-value'],
            prompt: 'You own 12 shares bought at $4.00. The price is now $4.75. What is the position worth?',
            unit: 'usd',
            answer: d(57),
            tolerance: 0,
            inputLabel: 'Position value in dollars',
            misconceptions: [
              { value: d(9), misconception: 'value-vs-gain', feedback: '$9 is the unrealized gain (12 × $0.75). Value is 12 × $4.75.' },
              { value: d(48), misconception: 'cost-not-value', feedback: '$48 is what you paid. Use the current price.' },
            ],
            wrongFeedback: 'Value = 12 × $4.75.',
            explanation: '12 × $4.75 = $57. The unrealized gain is $57 − $48 = $9.',
          },
        },
        {
          kind: 'exercise',
          id: 'cp-realized',
          exercise: {
            id: 'u1-cp-realized-loss',
            kind: 'numeric',
            skills: ['profit-loss'],
            prompt: 'You buy 5 shares at $30.00 and sell all 5 at $29.20. The fee is $0.50 per trade. What is the realized result?',
            unit: 'usd',
            answer: d(-5),
            tolerance: 0,
            inputLabel: 'Realized result in dollars (use a minus sign for a loss)',
            misconceptions: [
              { value: d(-4), misconception: 'ignore-fees', feedback: '−$4 is the price loss. Both fees add another $1.00 of loss.' },
              { value: d(5), misconception: 'sign', feedback: 'The size is right, but this is a loss: you sold for less than you paid.' },
              { value: d(-3), misconception: 'fees-reduce-loss', feedback: 'Fees never reduce a loss. They add to it.' },
            ],
            wrongFeedback: 'Received (5 × $29.20) − paid (5 × $30.00) − fees ($1.00).',
            explanation: '$146 − $150 − $1 = −$5.',
          },
        },
        {
          kind: 'exercise',
          id: 'cp-horizon',
          exercise: {
            id: 'u1-cp-horizon',
            kind: 'choice',
            skills: ['investing-vs-trading'],
            prompt: 'A friend says, “I’ll hold this for ten years, but I check the price daily.” Is that trading or investing?',
            options: [
              { id: 'a', text: 'Investing: the plan is to hold for years, even if they look often.', correct: true, feedback: 'Right. The holding plan matters, not how often you look.' },
              { id: 'b', text: 'Trading, because they check daily.', misconception: 'checking-is-trading', feedback: 'Looking is not trading. Trading means buying and selling often.' },
              { id: 'c', text: 'Neither, because nothing was sold.', misconception: 'must-sell', feedback: 'Buying and holding for the long term is investing.' },
            ],
            explanation: 'Time horizon and how often you buy and sell define the difference.',
          },
        },
        {
          kind: 'exercise',
          id: 'cp-diversify',
          exercise: {
            id: 'u1-cp-diversification',
            kind: 'choice',
            skills: ['diversification'],
            prompt: 'Which statement about diversification is accurate?',
            options: [
              { id: 'a', text: 'It can reduce the damage from one bad investment, but losses are still possible.', correct: true, feedback: 'Yes. It spreads risk; it doesn’t erase it.' },
              { id: 'b', text: 'A diversified portfolio cannot lose money.', misconception: 'diversification-guarantee', feedback: 'Diversified holdings can still fall together. It reduces some risks only.' },
              { id: 'c', text: 'Diversification means buying and selling more often.', misconception: 'trading-diversifies', feedback: 'That describes trading. Diversification is about spreading across investments.' },
            ],
            explanation: 'Diversification spreads money across different investments to reduce the effect of any one of them.',
          },
        },
      ],
      recap: ['You valued positions, calculated a realized loss with fees, and separated trading, investing and diversification.'],
      glossary: ['cost-basis', 'realized-gain', 'diversification'],
      sources: ['sec-stocks', 'sec-diversification'],
      review: { skills: ['position-value', 'profit-loss', 'investing-vs-trading', 'diversification'] },
      help: {
        simpler: 'Value: multiply shares by today’s price. Result after selling: money in − money out − fees.',
        example: '3 shares bought at $10, sold at $11, $0.50 fees: $33 − $30 − $1 = $2.',
      },
    },
  ],
};
