import type { Unit } from '../schema';

const REASONING = 'Graded on reasoning with an instructor-defined rubric. The unseen next candle is not part of the grade.';

export const unit08: Unit = {
  id: 'u8',
  number: 8,
  title: 'Emotions, pressure and scams',
  summary: 'Recognize chasing, revenge trading and moved stops, and spot the red flags regulators warn about.',
  lessons: [
    {
      id: 'u8-fomo',
      version: 1,
      unitId: 'u8',
      kind: 'lesson',
      title: 'Fear of missing out',
      objective: 'Recognize when a trade idea comes from excitement rather than a plan.',
      minutes: 3,
      prerequisites: ['u7-checkpoint'],
      contentType: 'scenario',
      steps: [
        {
          kind: 'concept',
          id: 'chasing',
          title: 'Chasing a move',
          body:
            '[[fomo]] is the urge to jump in because a price is moving and others seem to be profiting.\n\nThe signs: no setup, no stop, a feeling of urgency, and a reason that starts with “everyone”. The move you see has already happened. What matters is the risk from here, and whether it fits your plan.',
        },
        {
          kind: 'exercise',
          id: 'buzz',
          exercise: {
            id: 'u8-social-buzz',
            kind: 'decision',
            skills: ['fomo'],
            prompt: 'Choose an action and the best reason.',
            situation:
              'A fictional stock is up 12% in 20 minutes. A forum thread is full of rocket emojis. There is no pullback, no clear support nearby, and you have no written plan for it.',
            actions: [
              { id: 'buy', text: 'Buy now' },
              { id: 'pass', text: 'Pass and keep watching' },
            ],
            reasons: [
              { id: 'r1', text: 'There’s no setup and no invalidation level, so I can’t size or plan the risk.', points: 2, supports: ['pass'], feedback: 'Strong: you tied the decision to what the plan needs.' },
              { id: 'r2', text: 'So many people can’t all be wrong.', points: 0, supports: ['buy'], misconception: 'crowd-proof', feedback: 'Popularity isn’t a setup, and online buzz can be coordinated.' },
              { id: 'r3', text: 'I’ll buy a small amount so it doesn’t matter.', points: 0, supports: ['buy'], misconception: 'small-means-safe', feedback: 'Small size doesn’t turn an unplanned trade into a plan. It builds a chasing habit.' },
              { id: 'r4', text: 'It has gone up too much, so it must fall.', points: 1, supports: ['pass'], misconception: 'prediction', feedback: 'Passing is right, but a guess about the next move isn’t the reason. The missing plan is.' },
            ],
            explanation: 'With no setup and no stop, there’s nothing to trade. Watching is a fine outcome.',
            rubricNote: REASONING,
          },
        },
        {
          kind: 'exercise',
          id: 'signs',
          exercise: {
            id: 'u8-chasing-signs',
            kind: 'choice',
            skills: ['fomo'],
            prompt: 'Which thought is the clearest warning sign of chasing?',
            options: [
              { id: 'a', text: '“If I don’t get in now, I’ll miss it.”', correct: true, feedback: 'Yes. Urgency without a plan is the core of FOMO.' },
              { id: 'b', text: '“My stop would be at $18.40, below the swing low.”', misconception: 'plan-is-fomo', feedback: 'That’s a planning thought, not chasing.' },
              { id: 'c', text: '“The setup isn’t there yet, so I’ll wait.”', misconception: 'waiting-is-fomo', feedback: 'That’s the opposite of chasing: it’s choosing to wait.' },
            ],
            explanation: 'Urgency is the signal. Plans don’t expire in seconds.',
          },
        },
      ],
      recap: ['FOMO is urgency without a plan.', 'The move you see already happened; only the risk from here matters.'],
      glossary: ['fomo', 'invalidation'],
      sources: ['sec-social-media-scams'],
      review: { skills: ['fomo'] },
      help: {
        simpler: 'If you feel you must act right now, that feeling is the warning. Good setups let you plan first.',
        example: 'A stock jumps 10% and your chat is excited. You have no stop level. Decision: pass, and add it to a watchlist.',
      },
    },
    {
      id: 'u8-revenge',
      version: 1,
      unitId: 'u8',
      kind: 'lesson',
      title: 'Revenge trades and moved stops',
      objective: 'Keep the risk limit after a loss and never widen a stop to avoid being wrong.',
      minutes: 4,
      prerequisites: ['u8-fomo'],
      contentType: 'scenario',
      steps: [
        {
          kind: 'concept',
          id: 'revenge',
          title: 'After a loss',
          body:
            '[[revenge-trading]] means taking bigger or faster trades to win back a loss. Moving a stop lower is its quiet cousin: you avoid admitting the idea was wrong, and the loss grows.\n\nThe stop was placed at [[invalidation]]. If price gets there, the plan said the idea is wrong. Moving it changes the risk you agreed to.',
        },
        {
          kind: 'exercise',
          id: 'move-stop',
          exercise: {
            id: 'u8-move-stop',
            kind: 'decision',
            skills: ['revenge-risk'],
            prompt: 'Choose an action and the best reason.',
            situation: 'You own 20 shares from $30.00 with a stop at $29.50 (risk $10). The bid is now $29.60 and falling. You think it will bounce.',
            actions: [
              { id: 'keep', text: 'Keep the stop at $29.50' },
              { id: 'lower', text: 'Move the stop to $28.50' },
            ],
            reasons: [
              { id: 'r1', text: 'The stop marks where the idea is wrong; moving it would double my planned risk.', points: 2, supports: ['keep'], feedback: 'Yes. Widening the stop turns a $10 risk into $30.' },
              { id: 'r2', text: 'It will bounce, so a lower stop gives it room.', points: 0, supports: ['lower'], misconception: 'hope-stop', feedback: 'That’s hope, not a plan. The plan’s invalidation hasn’t changed.' },
              { id: 'r3', text: 'Keep it, because I’d be embarrassed to lose more.', points: 1, supports: ['keep'], misconception: 'emotional-reason', feedback: 'Right action, but the reason is a feeling. The plan and risk budget are the reason.' },
            ],
            explanation: 'A stop can be tightened to protect gains, but widening it breaks the risk plan. The journal flags widened stops.',
            rubricNote: REASONING,
          },
        },
        {
          kind: 'exercise',
          id: 'trap-or-discipline',
          exercise: {
            id: 'u8-trap-sort',
            kind: 'categorize',
            skills: ['revenge-risk'],
            prompt: 'Sort each behavior after a losing trade.',
            categories: [
              { id: 'trap', label: 'Risk trap' },
              { id: 'disciplined', label: 'Disciplined' },
            ],
            items: [
              { id: 'double', text: 'Doubling size on the next trade to win it back', category: 'trap', feedback: 'That’s revenge trading: more risk to fix a feeling.' },
              { id: 'break', text: 'Taking a break before the next trade', category: 'disciplined', feedback: 'A pause helps you return to the plan.' },
              { id: 'lower', text: 'Moving an open trade’s stop further away', category: 'trap', feedback: 'Widening a stop increases the loss you agreed to.' },
              { id: 'tighten', text: 'Raising a stop to lock in part of a gain, as planned', category: 'disciplined', feedback: 'Tightening a stop reduces risk; that’s allowed by most plans.' },
              { id: 'skip', text: 'Skipping the journal because the loss feels bad', category: 'trap', feedback: 'Losing trades are the most useful ones to review.' },
              { id: 'same', text: 'Keeping the same risk budget on the next setup', category: 'disciplined', feedback: 'Consistent risk keeps one result from dominating.' },
            ],
            explanation: 'Traps add risk or skip review. Discipline keeps risk steady and reviews honestly.',
            rubricNote: 'Instructor-defined categories based on the course’s risk rules.',
          },
        },
      ],
      recap: ['Don’t increase size to win back a loss.', 'Never widen a stop; tightening is fine.', 'Review losing trades, don’t hide them.'],
      glossary: ['revenge-trading', 'invalidation', 'risk-budget'],
      sources: ['finra-frequent-trading'],
      review: { skills: ['revenge-risk'] },
      help: {
        simpler: 'After a loss, the next trade should look exactly like the plan says, same size and same kind of stop.',
        example: 'You lost $10. Next setup: still risk $10, not $20. Your stop stays where you placed it.',
      },
    },
    {
      id: 'u8-scams',
      version: 1,
      unitId: 'u8',
      kind: 'lesson',
      title: 'Scam signals',
      objective: 'Recognize common investment-fraud red flags and know how to check a seller.',
      minutes: 4,
      prerequisites: ['u8-revenge'],
      contentType: 'factual',
      steps: [
        {
          kind: 'concept',
          id: 'red-flags',
          title: 'What regulators warn about',
          body:
            'U.S. regulators list warning signs of investment fraud: guaranteed high returns with little risk, pressure to act now, unsolicited offers, unregistered sellers, and requests to pay in unusual ways.\n\nOnline, promoters may hype a stock to push its price up and then sell. Anyone selling “signals” or guaranteed profits deserves extra suspicion.',
          more: 'You can look up whether a person or firm is registered with Investor.gov’s search tools. This app never asks for money or account details.',
        },
        {
          kind: 'exercise',
          id: 'sort-messages',
          exercise: {
            id: 'u8-message-sort',
            kind: 'categorize',
            skills: ['scam-signals'],
            prompt: 'Sort each message by how concerning it is.',
            categories: [
              { id: 'red', label: 'Red flag' },
              { id: 'lower', label: 'Lower concern' },
            ],
            items: [
              { id: 'guarantee', text: '“Guaranteed 20% a month, zero risk.”', category: 'red', feedback: 'Guaranteed high returns with no risk are a classic warning sign.' },
              { id: 'vip', text: '“VIP signal chat closes tonight. Join now!”', category: 'red', feedback: 'Pressure to act now is a red flag.' },
              { id: 'gift', text: '“Pay the membership fee with gift cards.”', category: 'red', feedback: 'Unusual payment methods are a strong fraud signal.' },
              { id: 'edu', text: 'A regulator page explaining how limit orders work', category: 'lower', feedback: 'Educational material from a regulator isn’t selling anything.' },
              { id: 'check', text: 'A page telling you to check registration before investing', category: 'lower', feedback: 'Encouraging verification is a good sign.' },
            ],
            explanation: 'Guarantees, urgency and odd payment methods are red flags. Verification and plain education are lower concern.',
          },
        },
        {
          kind: 'exercise',
          id: 'stranger',
          exercise: {
            id: 'u8-stranger-signals',
            kind: 'choice',
            skills: ['scam-signals'],
            prompt: 'A stranger messages you offering trading signals for $200 and says their students “never lose”. What’s the best response?',
            options: [
              { id: 'a', text: 'Don’t send money; check whether they’re registered and treat the “never lose” claim as a warning sign.', correct: true, feedback: 'Yes. Unsolicited offers plus impossible claims are red flags.' },
              { id: 'b', text: 'Ask for screenshots of their profits first.', misconception: 'screenshots-prove', feedback: 'Screenshots are easy to fake and show only the winners.' },
              { id: 'c', text: 'Try one month; $200 is a small amount.', misconception: 'small-cost', feedback: 'The cost isn’t the issue. The claims are the warning.' },
            ],
            explanation: 'No one can promise trading never loses. Verify before you trust.',
          },
        },
      ],
      recap: ['Guarantees, urgency and odd payment methods are red flags.', 'Check registration before trusting a seller.', 'No one can promise trades never lose.'],
      glossary: ['fomo'],
      sources: ['sec-red-flags', 'sec-social-media-scams'],
      review: { skills: ['scam-signals'] },
      help: {
        simpler: 'If someone promises big, sure profits and wants you to hurry, treat it as a scam until proven otherwise.',
        example: '“Join my group, 30% a week guaranteed, pay by crypto today.” Three red flags: guarantee, urgency, odd payment.',
      },
    },
    {
      id: 'u8-checkpoint',
      version: 1,
      unitId: 'u8',
      kind: 'checkpoint',
      title: 'Unit 8 checkpoint',
      objective: 'Handle pressure, losses and suspicious offers in new situations.',
      minutes: 3,
      prerequisites: ['u8-scams'],
      contentType: 'scenario',
      steps: [
        { kind: 'concept', id: 'intro', title: 'Under pressure', body: 'Three new situations. Focus on the plan and on red flags, not on what price might do next.' },
        {
          kind: 'exercise',
          id: 'cp-streak',
          exercise: {
            id: 'u8-cp-after-streak',
            kind: 'decision',
            skills: ['revenge-risk', 'fomo'],
            prompt: 'Choose an action and the best reason.',
            situation: 'You’ve lost three practice trades in a row. A fast-moving stock catches your eye. You want to buy 3× your usual size “to get back to even”.',
            actions: [
              { id: 'buy', text: 'Buy 3× size' },
              { id: 'stop', text: 'Stop for now and review the three trades' },
            ],
            reasons: [
              { id: 'r1', text: 'Tripling size to recover is revenge trading, and this trade isn’t in my plan.', points: 2, supports: ['stop'], feedback: 'Yes. You named both problems: size and no plan.' },
              { id: 'r2', text: 'A win now would fix the week.', points: 0, supports: ['buy'], misconception: 'revenge', feedback: 'Trying to fix past results with bigger risk is the trap.' },
              { id: 'r3', text: 'Three losses mean my luck is due to turn.', points: 0, supports: ['buy'], misconception: 'gamblers-fallacy', feedback: 'Past results don’t make the next one more likely to win.' },
            ],
            explanation: 'Stepping back and reviewing is the disciplined choice here.',
            rubricNote: REASONING,
          },
        },
        {
          kind: 'exercise',
          id: 'cp-tighten',
          exercise: {
            id: 'u8-cp-stop-change',
            kind: 'choice',
            skills: ['revenge-risk'],
            prompt: 'You bought at $40.00 with a stop at $39.00. Price is now $42.00. Which stop change keeps within the plan’s risk rules?',
            options: [
              { id: 'a', text: 'Raise the stop to $40.50', correct: true, feedback: 'Yes. Tightening reduces risk; the worst case is now a small gain before costs.' },
              { id: 'b', text: 'Lower the stop to $38.00', misconception: 'widen-stop', feedback: 'Widening increases the loss you agreed to.' },
              { id: 'c', text: 'Remove the stop, since the trade is winning', misconception: 'remove-stop', feedback: 'Without a stop, a gap or reversal could erase the gain and more.' },
            ],
            explanation: 'Stops may only move in the direction that reduces risk.',
          },
        },
        {
          kind: 'exercise',
          id: 'cp-scam',
          exercise: {
            id: 'u8-cp-pump',
            kind: 'choice',
            skills: ['scam-signals'],
            prompt: 'Many new accounts post the same message: “This tiny stock will 10× by Friday, buy before the news!” What is the most likely risk?',
            options: [
              { id: 'a', text: 'A coordinated promotion to push the price up before promoters sell.', correct: true, feedback: 'Yes. Regulators warn about this pattern on social media.' },
              { id: 'b', text: 'Insider knowledge you can safely use.', misconception: 'insider-tip', feedback: 'Anonymous hype is not reliable information, and acting on real inside information can be illegal.' },
              { id: 'c', text: 'Normal market enthusiasm with no special risk.', misconception: 'normal-hype', feedback: 'Identical posts from new accounts plus a deadline are red flags.' },
            ],
            explanation: 'Coordinated hype with a deadline is a common pump pattern.',
          },
        },
      ],
      recap: ['You chose to step back after losses, tightened rather than widened a stop, and spotted a likely promotion.'],
      glossary: ['revenge-trading', 'fomo'],
      sources: ['sec-social-media-scams'],
      review: { skills: ['fomo', 'revenge-risk', 'scam-signals'] },
      help: { simpler: 'Same size, stops only tighten, and hype with a deadline is a warning.', example: 'Up $2 on a trade: raise the stop, don’t remove it.' },
    },
  ],
};
