import type { Unit } from '../schema';
import { d, fromCloses } from '../helpers';

const REASONING = 'Graded on reasoning with an instructor-defined rubric. The unseen next candle is not part of the grade.';

export const unit10: Unit = {
  id: 'u10',
  number: 10,
  title: 'Test an idea honestly',
  summary: 'Turn an idea into a testable setup, practice without hindsight, and review your own readiness.',
  lessons: [
    {
      id: 'u10-hypothesis',
      version: 1,
      unitId: 'u10',
      kind: 'lesson',
      title: 'A testable setup',
      objective: 'Rewrite a vague idea as a setup with a clear trigger, invalidation and exit.',
      minutes: 4,
      prerequisites: ['u9-checkpoint'],
      contentType: 'scenario',
      steps: [
        {
          kind: 'concept',
          id: 'testable',
          title: 'Vague ideas can’t be tested',
          body:
            '“Buy strong stocks” can’t be tested: you can’t tell if you followed it.\n\nA testable [[hypothesis]] says exactly when you enter, where you are wrong, and when you exit. For example: “After a pullback to a support zone, buy when a candle closes back above the zone. Stop below the zone. Target 2R.”\n\nThen you can count results honestly.',
        },
        {
          kind: 'exercise',
          id: 'pick-testable',
          exercise: {
            id: 'u10-pick-testable',
            kind: 'choice',
            skills: ['hypothesis'],
            prompt: 'Which idea is testable as written?',
            options: [
              { id: 'a', text: 'Buy when a candle closes above the prior swing high; stop below the last swing low; exit at 2R or after 20 candles.', correct: true, feedback: 'Yes. Entry, invalidation and exit are all defined.' },
              { id: 'b', text: 'Buy stocks that look ready to go up.', misconception: 'vague-setup', feedback: '“Look ready” can’t be checked. Two people would disagree on every chart.' },
              { id: 'c', text: 'Buy on breakouts and sell when it feels right.', misconception: 'vague-exit', feedback: 'The entry is roughly defined, but “feels right” can’t be tested.' },
            ],
            explanation: 'A setup is testable when someone else could follow it and get the same trades.',
          },
        },
        {
          kind: 'exercise',
          id: 'build-hypothesis',
          exercise: {
            id: 'u10-hypothesis-parts',
            kind: 'categorize',
            skills: ['hypothesis'],
            prompt: 'Sort each phrase into the part of the setup it defines.',
            categories: [
              { id: 'entry', label: 'Entry trigger' },
              { id: 'invalid', label: 'Invalidation' },
              { id: 'exit', label: 'Exit' },
            ],
            items: [
              { id: 'close-above', text: 'A candle closes back above the support zone', category: 'entry', feedback: 'That’s the event that triggers the buy.' },
              { id: 'below-zone', text: 'Price trades below the bottom of the zone', category: 'invalid', feedback: 'That’s where the idea is proven wrong.' },
              { id: 'two-r', text: 'Sell when profit reaches 2R', category: 'exit', feedback: 'A profit rule defines the exit.' },
              { id: 'time', text: 'Sell if nothing has happened after 20 candles', category: 'exit', feedback: 'A time exit is also an exit rule.' },
            ],
            explanation: 'Each part must be specific enough to check on a chart.',
            rubricNote: 'Instructor-defined categories.',
          },
        },
      ],
      recap: ['A testable setup defines entry, invalidation and exit.', 'If you can’t check it, you can’t test it.'],
      glossary: ['hypothesis', 'invalidation', 'r-multiple'],
      sources: [],
      review: { skills: ['hypothesis'] },
      help: {
        simpler: 'Write the setup so clearly that a friend could follow it without asking you questions.',
        example: '“Buy when price closes above $50 resistance; stop at $49; target $52.” A friend could test that.',
      },
    },
    {
      id: 'u10-no-hindsight',
      version: 1,
      unitId: 'u10',
      kind: 'lesson',
      title: 'No peeking at the future',
      objective: 'Make decisions using only information available at the time.',
      minutes: 4,
      prerequisites: ['u10-hypothesis'],
      contentType: 'scenario',
      steps: [
        {
          kind: 'concept',
          id: 'hindsight',
          title: 'The chart looks obvious later',
          body:
            'On a finished chart, the best entries look obvious. At the time, the right side of the chart was blank.\n\n[[hindsight-bias]] makes past setups look easier than they were, and makes a method look better than it is. The simulator helps by revealing one quote at a time and filling orders only on quotes you haven’t seen yet.',
        },
        {
          kind: 'exercise',
          id: 'available',
          exercise: {
            id: 'u10-available-info',
            kind: 'categorize',
            skills: ['no-hindsight'],
            prompt: 'You are deciding at the close of candle 12. Sort each piece of information.',
            categories: [
              { id: 'known', label: 'Known at the time' },
              { id: 'hindsight', label: 'Hindsight' },
            ],
            items: [
              { id: 'close12', text: 'Candle 12’s close', category: 'known', feedback: 'It just closed, so you can use it.' },
              { id: 'swing', text: 'A swing low confirmed by candles 9 and 10', category: 'known', feedback: 'It was confirmed before candle 12 closed.' },
              { id: 'high15', text: 'The high of candle 15', category: 'hindsight', feedback: 'Candle 15 hasn’t happened yet.' },
              { id: 'swing11', text: 'A swing low at candle 11', category: 'hindsight', feedback: 'It needs two later candles to be confirmed; only one has closed.' },
              { id: 'end', text: 'Where the scenario finishes', category: 'hindsight', feedback: 'The ending is unknown while you trade.' },
            ],
            explanation: 'Only use closed candles and swing points already confirmed.',
          },
        },
        {
          kind: 'exercise',
          id: 'replay',
          exercise: {
            id: 'u10-replay-decision',
            kind: 'decision',
            skills: ['no-hindsight'],
            prompt: 'Choose an action and the best reason.',
            situation:
              'You’re reviewing a finished scenario. At candle 8 your setup was not present, so you passed. Looking at the full chart now, price rose steadily after candle 8.',
            visual: {
              kind: 'candles',
              candles: fromCloses(20, [20.2, 20.1, 20.3, 20.2, 20.4, 20.3, 20.2, 20.5, 20.9, 21.2, 21.6, 21.9]),
              highlight: [7],
              caption: 'Finished scenario. Candle 8 is highlighted; the rise after it was not visible at the time.',
            },
            actions: [
              { id: 'keep', text: 'Keep the pass as a sound decision' },
              { id: 'mark', text: 'Mark the pass as a mistake' },
            ],
            reasons: [
              { id: 'r1', text: 'At candle 8 the setup wasn’t there; the later rise wasn’t known.', points: 2, supports: ['keep'], feedback: 'Yes. You judged with the information available at the time.' },
              { id: 'r2', text: 'The chart clearly went up, so I should have bought.', points: 0, supports: ['mark'], misconception: 'hindsight', feedback: 'That uses candles 9–12, which you couldn’t see.' },
              { id: 'r3', text: 'I should change my setup so it would have caught this move.', points: 0, supports: ['mark'], misconception: 'curve-fit', feedback: 'Changing rules to fit one past chart makes the method look better than it is.' },
            ],
            explanation: 'A pass is judged by what was known at candle 8, not what happened next.',
            rubricNote: REASONING,
          },
        },
      ],
      recap: ['Use only closed candles and confirmed swings.', 'Don’t change rules to fit one past chart.'],
      glossary: ['hindsight-bias', 'swing-low'],
      sources: [],
      review: { skills: ['no-hindsight'] },
      help: {
        simpler: 'Imagine covering the right side of the chart with your hand. Decide only from what’s left.',
        example: 'A breakout that “obviously” worked might have looked like the failed breakout the week before, at the time.',
      },
    },
    {
      id: 'u10-capstone',
      version: 1,
      unitId: 'u10',
      kind: 'lesson',
      title: 'Capstone plan and self-review',
      objective: 'Size a full plan with costs, and judge your own readiness honestly.',
      minutes: 5,
      prerequisites: ['u10-no-hindsight'],
      contentType: 'scenario',
      steps: [
        {
          kind: 'concept',
          id: 'together',
          title: 'Putting it together',
          body:
            'A complete practice trade uses everything: a testable setup, a stop at invalidation, a size from your [[risk-budget]] including costs, a target, and a journal entry.\n\nReadiness isn’t a feeling or a profit. It’s evidence: many simulated trades where you followed the plan, with honest records of the losses too.',
        },
        {
          kind: 'exercise',
          id: 'capstone-size',
          exercise: {
            id: 'u10-capstone-size',
            kind: 'risk-build',
            skills: ['position-sizing', 'costs-slippage'],
            prompt: 'Entry $12.40, stop $12.00, target $13.20. Budget $10.00 including a $0.50 fee on each fill and $0.01 slippage per share on entry and exit. Choose the largest size that fits.',
            cash: d(1000),
            riskBudget: d(10),
            feePerFill: 50,
            slippagePerShare: 1,
            start: { entry: d(12.4), stop: d(12), target: d(13.2), shares: 25 },
            adjustable: ['shares'],
            priceStep: 1,
            rubric: { type: 'max-shares-within-budget', includeCosts: true },
            wrongFeedback: 'Subtract both fees from the budget, then divide by the stop distance plus slippage on both fills.',
            explanation: '($10.00 − $1.00 fees) ÷ ($0.40 + $0.02 slippage) = 21.4, so 21 shares. Planned worst case: 21 × $0.42 + $1.00 = $9.82.',
          },
        },
        {
          kind: 'exercise',
          id: 'self-review',
          exercise: {
            id: 'u10-readiness',
            kind: 'decision',
            skills: ['self-review'],
            prompt: 'Choose an action and the best reason.',
            situation:
              'After 12 simulated trades you’re up $40 virtual. You followed your plan on 7 of them. You feel confident.',
            actions: [
              { id: 'continue', text: 'Keep practicing and reviewing' },
              { id: 'ready', text: 'Decide you’ve mastered trading' },
            ],
            reasons: [
              { id: 'r1', text: 'The sample is small and I broke the plan on 5 trades; I need more consistent evidence.', points: 2, supports: ['continue'], feedback: 'Yes. You weighed sample size and adherence, not profit.' },
              { id: 'r2', text: 'I’m profitable, so the method works.', points: 0, supports: ['ready'], misconception: 'outcome-bias', feedback: 'Twelve trades and a small profit can’t separate skill from luck.' },
              { id: 'r3', text: 'Confidence is the best sign of readiness.', points: 0, supports: ['ready'], misconception: 'confidence', feedback: 'Feelings aren’t evidence. Plan adherence and sample size are.' },
              { id: 'r4', text: 'Keep practicing because I might lose next time.', points: 1, supports: ['continue'], misconception: 'vague-worry', feedback: 'Right choice, but the reason is vague. Point to the evidence: 7 of 12 followed.' },
            ],
            explanation: 'Readiness comes from consistent plan-following over many trades, not from a profit.',
            rubricNote: REASONING,
          },
        },
      ],
      recap: ['Costs reduce the size a budget allows.', 'Readiness is consistent evidence, not profit or confidence.'],
      glossary: ['risk-budget', 'fee', 'slippage', 'sample-size'],
      sources: ['finra-frequent-trading'],
      review: { skills: ['position-sizing', 'costs-slippage', 'self-review'] },
      help: {
        simpler: 'Take off the fees first, then see how many shares fit in what’s left. For readiness, count how often you followed the plan.',
        example: 'Budget $20, fees $1 total, stop distance $0.50 + $0.02 slippage → (20 − 1) ÷ 0.52 = 36 shares.',
      },
    },
    {
      id: 'u10-checkpoint',
      version: 1,
      unitId: 'u10',
      kind: 'checkpoint',
      title: 'Final checkpoint',
      objective: 'Show you can define, test and review an idea without hindsight.',
      minutes: 4,
      prerequisites: ['u10-capstone'],
      contentType: 'scenario',
      steps: [
        { kind: 'concept', id: 'intro', title: 'The last check', body: 'Three new situations covering testable setups, hindsight and self-review. Then keep practicing in the simulator.' },
        {
          kind: 'exercise',
          id: 'cp-testable',
          exercise: {
            id: 'u10-cp-fix-vague',
            kind: 'choice',
            skills: ['hypothesis'],
            prompt: 'Your note says: “Buy dips in uptrends.” Which rewrite makes it testable?',
            options: [
              { id: 'a', text: 'In an uptrend of higher swing highs and lows, buy when price closes back above the last swing low zone; stop $0.10 below that low; target 2R.', correct: true, feedback: 'Yes. Uptrend, dip, entry, stop and target are all checkable.' },
              { id: 'b', text: 'Buy dips in strong uptrends only.', misconception: 'vague-setup', feedback: '“Strong” still can’t be checked.' },
              { id: 'c', text: 'Buy dips in uptrends, and trust your gut on exits.', misconception: 'vague-exit', feedback: 'The exit still can’t be tested.' },
            ],
            explanation: 'Define each word with something you can see on a chart.',
          },
        },
        {
          kind: 'exercise',
          id: 'cp-hindsight',
          exercise: {
            id: 'u10-cp-backtest-claim',
            kind: 'choice',
            skills: ['no-hindsight'],
            prompt: 'A friend says their rule “wins 90%” after they adjusted it until it fit last month’s chart. What is the main problem?',
            options: [
              { id: 'a', text: 'The rule was fitted to results already known, so the 90% overstates how it would do on new data.', correct: true, feedback: 'Yes. Test on data the rule wasn’t tuned on.' },
              { id: 'b', text: 'Nothing; 90% is proof.', misconception: 'curve-fit', feedback: 'A rule tuned to the past will look good on that same past.' },
              { id: 'c', text: 'The only problem is the win rate is too high to be believable.', misconception: 'win-rate-only', feedback: 'The deeper problem is how it was built: by fitting to known results.' },
            ],
            explanation: 'Rules fitted to known results need fresh, unseen data before they mean anything.',
          },
        },
        {
          kind: 'exercise',
          id: 'cp-review',
          exercise: {
            id: 'u10-cp-self-review',
            kind: 'categorize',
            skills: ['self-review'],
            prompt: 'Sort each statement: is it evidence of progress, or not evidence?',
            categories: [
              { id: 'evidence', label: 'Evidence of progress' },
              { id: 'not', label: 'Not evidence' },
            ],
            items: [
              { id: 'adherence', text: 'Followed the written plan on 28 of 30 simulated trades', category: 'evidence', feedback: 'Consistent adherence across many trades is real evidence.' },
              { id: 'journal', text: 'Wrote a reflection for every losing trade', category: 'evidence', feedback: 'Honest review of losses shows discipline.' },
              { id: 'profit', text: 'Up $60 virtual after 5 trades', category: 'not', feedback: 'Five results can’t separate skill from luck.' },
              { id: 'feeling', text: 'Feeling ready', category: 'not', feedback: 'Feelings aren’t evidence.' },
              { id: 'stops', text: 'Never widened a stop in 30 trades', category: 'evidence', feedback: 'Keeping risk rules is a key habit.' },
            ],
            explanation: 'Progress is shown by consistent process over many trades.',
            rubricNote: 'Instructor-defined categories.',
          },
        },
      ],
      recap: ['You made a vague idea testable, spotted a curve-fitted claim, and separated evidence from feelings.'],
      glossary: ['hypothesis', 'hindsight-bias', 'sample-size'],
      sources: [],
      review: { skills: ['hypothesis', 'no-hindsight', 'self-review'] },
      help: { simpler: 'Clear rules, no peeking, and judge yourself by process over many trades.', example: '28 of 30 trades by the plan beats +$60 in 5 trades.' },
    },
  ],
};
