import type { Unit } from '../schema';
import { d } from '../helpers';

const REASONING = 'Graded on reasoning with an instructor-defined rubric. The unseen next candle is not part of the grade.';

export const unit07: Unit = {
  id: 'u7',
  number: 7,
  title: 'Build and execute a plan',
  summary: 'Write entry, invalidation and exit before trading; place and cancel orders; trade or pass by the plan.',
  lessons: [
    {
      id: 'u7-plan',
      version: 1,
      unitId: 'u7',
      kind: 'lesson',
      title: 'Entry, invalidation, exit',
      objective: 'Order the parts of a trade plan and put the stop where the idea is proven wrong.',
      minutes: 4,
      prerequisites: ['u6-checkpoint'],
      contentType: 'scenario',
      steps: [
        {
          kind: 'concept',
          id: 'parts',
          title: 'Write it before you trade',
          body:
            'A [[trade-plan]] is written before the trade.\nEntry: what has to happen for you to buy.\n[[invalidation]]: the price that shows the idea was wrong. The stop goes there.\nExit: a target, or a rule for taking profit.\nSize comes last, from the distance to invalidation and your risk budget.',
        },
        {
          kind: 'exercise',
          id: 'order-steps',
          exercise: {
            id: 'u7-plan-sequence',
            kind: 'sequence',
            skills: ['trade-plan'],
            prompt: 'Put the planning steps in a sensible order. Use the arrows to move items.',
            items: [
              { id: 'setup', text: 'Describe the setup you are waiting for', feedback: 'Start with the setup: without it there is nothing to plan.' },
              { id: 'invalid', text: 'Mark where the idea is proven wrong (invalidation)', feedback: 'Invalidation comes from the chart, before size or orders.' },
              { id: 'exit', text: 'Set a target or exit rule', feedback: 'Decide how you would take profit before entering.' },
              { id: 'size', text: 'Calculate size from the risk budget', feedback: 'Size depends on the stop distance, so it comes after invalidation.' },
              { id: 'place', text: 'Place the order with the stop attached', feedback: 'Orders go in last, once everything else is decided.' },
            ],
            correctOrder: ['setup', 'invalid', 'exit', 'size', 'place'],
            explanation: 'Setup → invalidation → exit → size → order. Size last, because it depends on where the stop is.',
            rubricNote: 'Instructor-defined order. Exit and size could reasonably swap in practice; this course teaches exit first.',
          },
        },
        {
          kind: 'exercise',
          id: 'stop-at-invalidation',
          exercise: {
            id: 'u7-stop-at-invalidation',
            kind: 'risk-build',
            skills: ['trade-plan', 'position-sizing'],
            prompt: 'The setup is wrong if price falls below the swing low at $24.50. Entry is $25.50, target $27.50, budget $20. Put the stop at invalidation, then size the trade (before costs).',
            cash: d(1000),
            riskBudget: d(20),
            feePerFill: 0,
            slippagePerShare: 0,
            start: { entry: d(25.5), stop: d(25), target: d(27.5), shares: 40 },
            adjustable: ['stop', 'shares'],
            priceStep: 10,
            rubric: { type: 'stop-at-invalidation', stop: d(24.5), shares: 20 },
            wrongFeedback: 'Move the stop to $24.50 first, then find the size that fits $20.',
            explanation: 'Stop at $24.50 is $1.00 below entry, so $20 ÷ $1.00 = 20 shares. A tighter stop would allow more shares, but it would sit inside normal movement and stop you out before the idea is actually wrong.',
            rubricNote: 'Instructor-defined rubric: the stop must match the stated invalidation.',
          },
        },
      ],
      recap: ['Plan before the trade: setup, invalidation, exit, size.', 'The stop goes at invalidation, not where it makes size look good.'],
      glossary: ['trade-plan', 'invalidation', 'risk-budget'],
      sources: [],
      review: { skills: ['trade-plan'] },
      help: {
        simpler: 'Decide where you’d admit you were wrong before you start. Then work out how many shares you can afford to be wrong with.',
        example: 'Setup: bounce from $40 support. Invalidation: close below $39.50. Target: $42. Budget $15 → 30 shares if entry is $40.00.',
      },
    },
    {
      id: 'u7-orders',
      version: 1,
      unitId: 'u7',
      kind: 'lesson',
      title: 'Placing and canceling simulated orders',
      objective: 'Predict pending, filled, canceled and rejected states in the simulator.',
      minutes: 3,
      prerequisites: ['u7-plan'],
      contentType: 'scenario',
      steps: [
        {
          kind: 'concept',
          id: 'states',
          title: 'How the simulator handles orders',
          body:
            'An order submitted while paused waits for the next quote. A pending buy holds [[reserved-cash]] so it can’t be spent twice. You can cancel anytime before it fills.\n\nAfter a buy fills, your stop and target start working together: when one fills, the other is canceled ([[oco]]).',
        },
        {
          kind: 'exercise',
          id: 'paused',
          exercise: {
            id: 'u7-paused-limit',
            kind: 'choice',
            skills: ['order-management'],
            prompt: 'You placed a buy limit at $15.00 while paused. The current ask is $15.20. What happens when you press “Next quote”?',
            options: [
              { id: 'a', text: 'The order is checked against the next quote; it fills only if that ask is $15.00 or lower.', correct: true, feedback: 'Yes. Orders are never filled on a quote you already saw.' },
              { id: 'b', text: 'It fills at $15.00 right away.', misconception: 'fill-while-paused', feedback: 'Nothing fills while paused, and a limit needs the ask to reach $15.00.' },
              { id: 'c', text: 'It fills at $15.20, the current ask.', misconception: 'limit-ignored', feedback: 'A buy limit never pays more than its limit.' },
            ],
            explanation: 'Orders wait for the next event and respect their limit price.',
          },
        },
        {
          kind: 'exercise',
          id: 'states-sort',
          exercise: {
            id: 'u7-order-states',
            kind: 'categorize',
            skills: ['order-management'],
            prompt: 'Sort each situation by the order state it produces.',
            categories: [
              { id: 'pending', label: 'Pending' },
              { id: 'filled', label: 'Filled' },
              { id: 'canceled', label: 'Canceled' },
              { id: 'rejected', label: 'Rejected' },
            ],
            items: [
              { id: 'i1', text: 'Buy limit at $9.00 while the ask is $10.00', category: 'pending', feedback: 'It waits until the ask reaches $9.00.' },
              { id: 'i2', text: 'Market buy, after the next quote arrives', category: 'filled', feedback: 'A market order fills on the next quote.' },
              { id: 'i3', text: 'You pressed cancel before it filled', category: 'canceled', feedback: 'Canceling a pending order removes it and releases reserved cash.' },
              { id: 'i4', text: 'The buy needs $1,200 but only $1,000 is available', category: 'rejected', feedback: 'Orders that can’t be paid for are rejected; there is no borrowing.' },
              { id: 'i5', text: 'Your target filled, so the linked stop is removed', category: 'canceled', feedback: 'One exit cancels the other so you can’t sell shares twice.' },
            ],
            explanation: 'Pending waits, filled executed, canceled was removed, rejected was never accepted or could not be paid for.',
          },
        },
      ],
      recap: ['Orders wait for the next quote.', 'Pending buys reserve cash.', 'Stop and target are linked: one cancels the other.'],
      glossary: ['reserved-cash', 'oco', 'take-profit'],
      sources: ['sec-order-types'],
      review: { skills: ['order-management'] },
      help: {
        simpler: 'Placing an order is like dropping a letter in a mailbox: nothing happens until the next pickup (the next quote).',
        example: 'You set a stop at $9 and target at $12. Price hits $12 first: sold at the target, and the $9 stop is removed.',
      },
    },
    {
      id: 'u7-trade-or-pass',
      version: 1,
      unitId: 'u7',
      kind: 'lesson',
      title: 'Trade or pass',
      objective: 'Decide whether to take a setup based on the plan, not excitement or recent results.',
      minutes: 4,
      prerequisites: ['u7-orders'],
      contentType: 'scenario',
      steps: [
        {
          kind: 'concept',
          id: 'pass',
          title: 'Passing is a skill',
          body:
            'Every setup ends in one of two decisions: take it as planned, or pass.\n\nPass when the setup isn’t there, when the stop would be too far for your budget, or when you notice you’re trading from excitement. A good decision follows the plan, whatever the next candle does.',
        },
        {
          kind: 'exercise',
          id: 'chase-or-pass',
          exercise: {
            id: 'u7-price-ran-away',
            kind: 'decision',
            skills: ['trade-or-pass'],
            prompt: 'Choose an action and the best reason.',
            situation: 'Your plan: buy a pullback to support near $30.00 with a stop at $29.40. Price never pulled back; it is now $31.20 and rising fast. With the stop still at $29.40, the risk would be three times your budget.',
            actions: [
              { id: 'take', text: 'Take the trade now' },
              { id: 'pass', text: 'Pass' },
            ],
            reasons: [
              { id: 'r1', text: 'The entry isn’t my setup and the risk to invalidation is far over budget.', points: 2, supports: ['pass'], feedback: 'Strong: it compares the situation with the plan and the budget.' },
              { id: 'r2', text: 'It’s moving, so I should get in before it’s gone.', points: 0, supports: ['take'], misconception: 'fomo', feedback: 'That is chasing. Momentum isn’t in the plan.' },
              { id: 'r3', text: 'I’ll buy a third of the size so the risk fits, even though this isn’t my entry.', points: 1, supports: ['take'], misconception: 'setup-drift', feedback: 'Sizing down fixes the risk, but the entry still isn’t your setup. That’s a new, untested plan.' },
              { id: 'r4', text: 'Pass, because it will probably crash.', points: 1, supports: ['pass'], misconception: 'prediction', feedback: 'Passing is right, but the reason is a guess. The plan is the reason.' },
            ],
            explanation: 'When price leaves without triggering the setup, the plan says pass.',
            rubricNote: REASONING,
          },
        },
        {
          kind: 'exercise',
          id: 'after-losses',
          exercise: {
            id: 'u7-after-two-losses',
            kind: 'decision',
            skills: ['trade-or-pass'],
            prompt: 'Choose an action and the best reason.',
            situation: 'Price pulled back to your support zone and printed the candle your plan describes. The stop fits your budget. Your last two practice trades lost, and you feel nervous.',
            actions: [
              { id: 'take', text: 'Take the trade as planned' },
              { id: 'pass', text: 'Pass' },
            ],
            reasons: [
              { id: 'r1', text: 'The setup and risk match the plan; the last two results don’t change this one.', points: 2, supports: ['take'], feedback: 'Yes. Two trades are too few to judge a setup, and the plan is being followed.' },
              { id: 'r2', text: 'Two losses mean the setup stopped working.', points: 0, supports: ['pass'], misconception: 'small-sample', feedback: 'Two results are a tiny sample. Losing streaks happen even with sound plans.' },
              { id: 'r3', text: 'Take it with double size to win back the losses.', points: 0, supports: ['take'], misconception: 'revenge', feedback: 'That is revenge trading: more risk to fix a feeling.' },
              { id: 'r4', text: 'I’m too rattled to follow the plan calmly, so I’ll pause and review first.', points: 1, supports: ['pass'], misconception: 'emotional-pass', feedback: 'A pause can be sensible if you truly can’t follow the plan, but here the plan is clear and within budget.' },
            ],
            explanation: 'Follow the plan when it applies; recent results aren’t a reason to change size or skip a valid setup.',
            rubricNote: REASONING,
          },
        },
      ],
      recap: ['Trade the plan or pass.', 'Recent wins or losses don’t change the plan.', 'Don’t resize to chase.'],
      glossary: ['trade-plan', 'fomo', 'revenge-trading'],
      sources: [],
      review: { skills: ['trade-or-pass'] },
      help: {
        simpler: 'If it isn’t on your shopping list, don’t buy it just because it’s on display.',
        example: 'Plan: buy at $20 support. Price jumps to $21.50 without touching $20. Decision: pass and wait for the next setup.',
      },
    },
    {
      id: 'u7-checkpoint',
      version: 1,
      unitId: 'u7',
      kind: 'checkpoint',
      title: 'Unit 7 checkpoint',
      objective: 'Plan, manage and decide in new situations.',
      minutes: 3,
      prerequisites: ['u7-trade-or-pass'],
      contentType: 'scenario',
      steps: [
        { kind: 'concept', id: 'intro', title: 'Putting the plan to work', body: 'New situations for planning, order handling and the trade-or-pass decision.' },
        {
          kind: 'exercise',
          id: 'cp-seq',
          exercise: {
            id: 'u7-cp-execution-sequence',
            kind: 'sequence',
            skills: ['trade-plan'],
            prompt: 'Order the steps of executing a written plan in the simulator.',
            items: [
              { id: 'check', text: 'Check the setup matches the written plan', feedback: 'First confirm the setup is actually there.' },
              { id: 'place', text: 'Place the buy with stop and target attached', feedback: 'Orders go in once the setup is confirmed.' },
              { id: 'fill', text: 'Step forward until the buy fills or you cancel it', feedback: 'Nothing is active until the entry fills.' },
              { id: 'verify', text: 'Confirm the stop and target are now pending', feedback: 'After the fill, check your protection is working.' },
              { id: 'journal', text: 'After the exit, write the reflection', feedback: 'Reflection comes after the trade is complete.' },
            ],
            correctOrder: ['check', 'place', 'fill', 'verify', 'journal'],
            explanation: 'Check → place → fill → verify protection → reflect.',
          },
        },
        {
          kind: 'exercise',
          id: 'cp-oco',
          exercise: {
            id: 'u7-cp-oco',
            kind: 'choice',
            skills: ['order-management'],
            prompt: 'You hold 12 shares with a stop at $18.00 and a target at $21.00. The bid reaches $21.05. What happens?',
            options: [
              { id: 'a', text: 'The target sells all 12 shares, and the stop is canceled automatically.', correct: true, feedback: 'Yes. Linked exits prevent selling twice.' },
              { id: 'b', text: 'Both orders fill, selling 24 shares.', misconception: 'oversell', feedback: 'You only own 12. The linked stop is canceled when the target fills.' },
              { id: 'c', text: 'The stop stays active to protect a new position.', misconception: 'orphan-stop', feedback: 'With no shares left, the stop is canceled.' },
            ],
            explanation: 'One-cancels-other links the two exits.',
          },
        },
        {
          kind: 'exercise',
          id: 'cp-pass',
          exercise: {
            id: 'u7-cp-wide-stop',
            kind: 'decision',
            skills: ['trade-or-pass'],
            prompt: 'Choose an action and the best reason.',
            situation: 'Your setup appears, but invalidation is $3.00 below entry. With your $15 budget that allows only 5 shares, and the target is just $2.00 above entry.',
            actions: [
              { id: 'take', text: 'Take it' },
              { id: 'pass', text: 'Pass' },
            ],
            reasons: [
              { id: 'r1', text: 'The reward is smaller than the planned risk, and my plan wants more reward than risk.', points: 2, supports: ['pass'], feedback: 'Good: you compared reward and risk against your own rule.' },
              { id: 'r2', text: 'Move the stop to $1.00 below entry so I can buy more shares.', points: 0, supports: ['take'], misconception: 'stop-for-size', feedback: 'That puts the stop where the idea isn’t wrong yet, just to make the size look better.' },
              { id: 'r3', text: 'Take it; setups are rare.', points: 0, supports: ['take'], misconception: 'scarcity', feedback: 'Rarity isn’t a reason. The numbers don’t fit the plan.' },
            ],
            explanation: 'Passing is correct when the plan’s conditions aren’t met, including reward versus risk.',
            rubricNote: REASONING,
          },
        },
      ],
      recap: ['You ordered execution steps, predicted linked exits, and passed on a trade that didn’t fit.'],
      glossary: ['oco', 'invalidation'],
      sources: [],
      review: { skills: ['trade-plan', 'order-management', 'trade-or-pass'] },
      help: { simpler: 'Plan, place, confirm, reflect. If the numbers don’t fit, pass.', example: 'Risk $3, reward $2 → pass.' },
    },
  ],
};
