import type { Unit } from '../schema';
import { d } from '../helpers';

const ARITH = 'Arithmetic practice with illustrative numbers — not a recommended trade or a suitable risk level for anyone.';

export const unit06: Unit = {
  id: 'u6',
  number: 6,
  title: 'Protect the practice account',
  summary: 'Position size from planned risk, reward versus risk, and why costs and gaps make losses bigger.',
  lessons: [
    {
      id: 'u6-size',
      version: 1,
      unitId: 'u6',
      kind: 'lesson',
      title: 'Position size from planned risk',
      objective: 'Calculate how many whole shares fit a planned risk budget.',
      minutes: 4,
      prerequisites: ['u5-checkpoint'],
      contentType: 'scenario',
      steps: [
        {
          kind: 'concept',
          id: 'arithmetic',
          title: 'Do the arithmetic first',
          body:
            'Planned risk per share = entry − stop.\nPlanned dollar risk = shares × risk per share.\n\nExample: virtual balance $1,000, a $10 [[risk-budget]], entry $20, stop $19. Risk per share is $1, so 10 shares is $10 of planned risk, before costs. The shares cost $200, which the balance covers.',
          more: ARITH,
          visual: { kind: 'plan', entry: d(20), stop: d(19), target: d(22), shares: 10, caption: 'Entry $20 · stop $19 · target $22 · 10 shares' },
        },
        {
          kind: 'exercise',
          id: 'builder',
          exercise: {
            id: 'u6-size-fixture',
            kind: 'risk-build',
            skills: ['position-sizing'],
            prompt: 'Adjust the share count to the largest whole number that keeps planned risk within the $10 budget (before costs).',
            cash: d(1000),
            riskBudget: d(10),
            feePerFill: 0,
            slippagePerShare: 0,
            start: { entry: d(20), stop: d(19), target: d(22), shares: 1 },
            adjustable: ['shares'],
            priceStep: 5,
            rubric: { type: 'max-shares-within-budget', includeCosts: false },
            wrongFeedback: 'Divide the budget by the risk per share and round down to a whole share.',
            explanation: '$10 ÷ $1 per share = 10 shares. Planned risk $10; potential reward 10 × $2 = $20.',
            rubricNote: ARITH,
          },
        },
        {
          kind: 'exercise',
          id: 'size-calc',
          exercise: {
            id: 'u6-size-calc',
            kind: 'numeric',
            skills: ['position-sizing'],
            prompt: 'Entry $50.00, stop $48.50, risk budget $30. How many whole shares fit the budget, before costs?',
            unit: 'shares',
            answer: 20,
            tolerance: 0,
            inputLabel: 'Whole shares',
            misconceptions: [
              { value: 0, misconception: 'budget-over-price', feedback: '$30 ÷ $50 compares the budget with the share price. Size comes from the risk per share: $50.00 − $48.50.' },
              { value: 60, misconception: 'wrong-risk-per-share', feedback: 'Check the risk per share: $50.00 − $48.50 = $1.50, not $0.50.' },
              { value: 15, misconception: 'wrong-risk-per-share', feedback: 'That uses $2 per share. The actual distance is $1.50.' },
            ],
            wrongFeedback: 'Shares = budget ÷ (entry − stop), rounded down.',
            explanation: '$30 ÷ $1.50 = 20 shares. That position costs $1,000, so cash also has to allow it.',
            rubricNote: ARITH,
          },
        },
      ],
      recap: ['Risk per share = entry − stop.', 'Shares = budget ÷ risk per share, rounded down.', 'Cash must also cover the purchase.'],
      glossary: ['risk-budget', 'position'],
      sources: [],
      review: { skills: ['position-sizing'] },
      help: {
        simpler: 'Decide how much you are willing to lose if you are wrong. Each share can lose (entry − stop). Divide to see how many shares that allows.',
        example: 'Budget $12, entry $8.00, stop $7.60: each share risks $0.40. $12 ÷ $0.40 = 30 shares.',
      },
    },
    {
      id: 'u6-reward-risk',
      version: 1,
      unitId: 'u6',
      kind: 'lesson',
      title: 'Planned risk and potential reward',
      objective: 'Calculate reward-to-risk and explain why the ratio alone doesn’t make a trade good.',
      minutes: 3,
      prerequisites: ['u6-size'],
      contentType: 'scenario',
      steps: [
        {
          kind: 'concept',
          id: 'ratio',
          visual: { kind: 'scene', scene: 'ladder', caption: 'Reward is the distance up to the target. Risk is the distance down to the stop.' },
          title: 'Reward compared with risk',
          body:
            'Potential reward = shares × (target − entry). [[reward-to-risk]] = potential reward ÷ planned risk.\n\nEntry $20, stop $19, target $22, 10 shares: reward $20, risk $10, so 2 to 1. A high ratio alone does not make a trade attractive: distant targets are usually reached less often.',
        },
        {
          kind: 'exercise',
          id: 'ratio-calc',
          exercise: {
            id: 'u6-ratio-calc',
            kind: 'numeric',
            skills: ['reward-risk'],
            prompt: 'Entry $40, stop $38, target $45. What is the reward-to-risk ratio? (Enter it as a number, e.g. 2 for 2-to-1.)',
            unit: 'ratio',
            answer: 2.5,
            tolerance: 0.01,
            inputLabel: 'Reward-to-risk ratio',
            misconceptions: [
              { value: 0.4, misconception: 'ratio-inverted', feedback: 'That is risk ÷ reward. Put the reward ($5) on top.' },
              { value: 5, misconception: 'reward-only', feedback: '$5 is the reward per share. Divide by the $2 risk per share.' },
              { value: 3.5, misconception: 'wrong-subtraction', feedback: 'Check both distances: $45 − $40 = $5 and $40 − $38 = $2.' },
            ],
            wrongFeedback: '(target − entry) ÷ (entry − stop).',
            explanation: '$5 ÷ $2 = 2.5, so 2.5 to 1. Share count cancels out.',
          },
        },
        {
          kind: 'exercise',
          id: 'ratio-not-enough',
          exercise: {
            id: 'u6-ratio-alone',
            kind: 'choice',
            skills: ['reward-risk'],
            prompt: 'Trade A offers 5-to-1, with a target far beyond any recent price. Trade B offers 1.5-to-1, with a target at a nearby, often-reached level. Which statement is most accurate?',
            options: [
              { id: 'a', text: 'The ratio alone can’t decide. How likely each target is matters too.', correct: true, feedback: 'Yes. A big ratio with a rarely-reached target can be worse than a modest one.' },
              { id: 'b', text: 'A is better because 5 is bigger than 1.5.', misconception: 'ratio-alone', feedback: 'The ratio ignores probability. A far target may almost never fill.' },
              { id: 'c', text: 'B is better because smaller targets always win.', misconception: 'small-target-always', feedback: 'Nothing “always” wins. Both need their likelihood considered.' },
            ],
            explanation: 'Reward-to-risk describes payoff size, not how often it happens.',
            rubricNote: 'Instructor-defined rubric: the accepted answer avoids judging by the ratio alone.',
          },
        },
      ],
      recap: ['Reward-to-risk = (target − entry) ÷ (entry − stop).', 'It ignores how likely the target is.'],
      glossary: ['reward-to-risk', 'risk-budget'],
      sources: [],
      review: { skills: ['reward-risk'] },
      help: {
        simpler: 'It compares how much you might gain with how much you plan to lose. But a lottery ticket has a huge ratio too — likelihood matters.',
        example: 'Entry $10, stop $9.50, target $11: reward $1, risk $0.50, ratio 2 to 1.',
      },
    },
    {
      id: 'u6-costs',
      version: 1,
      unitId: 'u6',
      kind: 'lesson',
      title: 'Costs, slippage and why stops are not guarantees',
      objective: 'Include fees and slippage in sizing, and explain why actual losses can exceed the plan.',
      minutes: 4,
      prerequisites: ['u6-reward-risk'],
      contentType: 'factual',
      steps: [
        {
          kind: 'concept',
          id: 'costs',
          visual: { kind: 'scene', scene: 'costs', caption: 'Fees and the spread shrink a gain and add to a loss.' },
          title: 'Every trade has costs',
          body:
            'This simulator charges a training [[fee]] on every fill and adds [[slippage]] to market-style fills. Real brokers and markets differ.\n\nCosts make losses bigger and gains smaller. FINRA notes that frequent trading brings higher costs that can erode returns.',
        },
        {
          kind: 'concept',
          id: 'not-guarantee',
          visual: { kind: 'scene', scene: 'gap', caption: 'A gap can carry price past the stop. The fill is the next available price.' },
          title: 'A stop is a trigger, not a ceiling on loss',
          body:
            'If price gaps below your stop, the order fills at the next available price. So plan with an allowance for costs and slippage, and keep size small enough that a worse-than-planned fill is survivable. Actual losses can still exceed the estimate.',
        },
        {
          kind: 'exercise',
          id: 'size-with-costs',
          exercise: {
            id: 'u6-size-with-costs',
            kind: 'risk-build',
            skills: ['costs-slippage', 'position-sizing'],
            prompt: 'Same idea, now with costs: $0.50 fee per fill (two fills) and $0.02 slippage per share on the way in and out. Find the largest whole-share size whose estimated risk stays within $10.',
            cash: d(1000),
            riskBudget: d(10),
            feePerFill: 50,
            slippagePerShare: 2,
            start: { entry: d(20), stop: d(19), target: d(22), shares: 10 },
            adjustable: ['shares'],
            priceStep: 5,
            rubric: { type: 'max-shares-within-budget', includeCosts: true },
            wrongFeedback: 'Estimated risk = shares × ($1.00 + $0.04 slippage) + $1.00 fees. Keep it at or under $10.',
            explanation: 'After $1.00 of fees, $9.00 remains. Each share risks $1.04 including slippage, so 8 shares ($9.32) fit; 9 shares would be $10.36.',
            rubricNote: ARITH,
          },
        },
        {
          kind: 'exercise',
          id: 'actual-loss',
          exercise: {
            id: 'u6-actual-loss',
            kind: 'numeric',
            skills: ['costs-slippage'],
            prompt: 'Plan: 10 shares, entry $20.00, stop $19.00 (planned risk $10). The fee is $0.50 per fill. The stop fills $0.02 below the stop price. What is the total loss?',
            unit: 'usd',
            answer: d(11.2),
            tolerance: 0,
            inputLabel: 'Total loss in dollars (as a positive number)',
            misconceptions: [
              { value: d(10), misconception: 'ignore-costs', feedback: '$10 is the plan before costs. Add the fees and the slippage.' },
              { value: d(11), misconception: 'ignore-slippage', feedback: 'You included the fees. Add 10 × $0.02 of slippage.' },
              { value: d(10.2), misconception: 'ignore-fees', feedback: 'You included slippage. Add the two $0.50 fees.' },
            ],
            wrongFeedback: 'Loss = 10 × ($20.00 − $18.98) + 2 × $0.50.',
            explanation: '10 × $1.02 = $10.20, plus $1.00 in fees = $11.20 — 12% more than planned, with no gap at all.',
          },
        },
      ],
      recap: ['Include fees and slippage when sizing.', 'Stops can fill worse than planned.', 'Keep size survivable, not maximal.'],
      glossary: ['fee', 'slippage', 'stop-order'],
      sources: ['finra-frequent-trading', 'finra-stop-orders'],
      review: { skills: ['costs-slippage', 'position-sizing'] },
      help: {
        simpler: 'The price you plan for is the best case. Fees and slippage are small leaks that are always there, and gaps are the occasional big leak.',
        example: '20 shares with $0.03 slippage adds $0.60 to the loss. Two $1 fees add $2.',
      },
    },
    {
      id: 'u6-checkpoint',
      version: 1,
      unitId: 'u6',
      kind: 'checkpoint',
      title: 'Unit 6 checkpoint',
      objective: 'Size, compare and cost a new plan.',
      minutes: 4,
      prerequisites: ['u6-costs'],
      contentType: 'scenario',
      steps: [
        { kind: 'concept', id: 'intro', title: 'New numbers', body: 'A new plan with different prices. Show the arithmetic still works.' , visual: { kind: 'scene', scene: 'ladder', caption: 'Same ladder, new prices.' }, },

        {
          kind: 'exercise',
          id: 'cp-size',
          exercise: {
            id: 'u6-cp-size',
            kind: 'risk-build',
            skills: ['position-sizing'],
            prompt: 'Entry $35.00, stop $33.50, budget $15, cash $1,000. Choose the largest whole-share size within budget (before costs).',
            cash: d(1000),
            riskBudget: d(15),
            feePerFill: 0,
            slippagePerShare: 0,
            start: { entry: d(35), stop: d(33.5), target: d(38), shares: 2 },
            adjustable: ['shares'],
            priceStep: 5,
            rubric: { type: 'max-shares-within-budget', includeCosts: false },
            wrongFeedback: '$15 ÷ $1.50 per share, rounded down.',
            explanation: '$15 ÷ $1.50 = 10 shares, costing $350.',
            rubricNote: ARITH,
          },
        },
        {
          kind: 'exercise',
          id: 'cp-ratio',
          exercise: {
            id: 'u6-cp-ratio',
            kind: 'numeric',
            skills: ['reward-risk'],
            prompt: 'Entry $12.00, stop $11.60, target $12.60. What is the reward-to-risk ratio?',
            unit: 'ratio',
            answer: 1.5,
            tolerance: 0.01,
            inputLabel: 'Reward-to-risk ratio',
            misconceptions: [
              { value: 0.67, tolerance: 0.02, misconception: 'ratio-inverted', feedback: 'That is risk ÷ reward. Reward goes on top.' },
              { value: 0.6, misconception: 'reward-only', feedback: '$0.60 is the reward per share. Divide by $0.40.' },
            ],
            wrongFeedback: '($12.60 − $12.00) ÷ ($12.00 − $11.60).',
            explanation: '$0.60 ÷ $0.40 = 1.5.',
          },
        },
        {
          kind: 'exercise',
          id: 'cp-stop',
          exercise: {
            id: 'u6-cp-stop-guarantee',
            kind: 'choice',
            skills: ['costs-slippage'],
            prompt: 'Which statement about a protective stop is accurate?',
            options: [
              { id: 'a', text: 'It triggers a sale near the stop price, but the loss can be larger because of gaps, slippage and fees.', correct: true, feedback: 'Yes. The plan is an estimate.' },
              { id: 'b', text: 'It guarantees the loss can’t exceed entry − stop.', misconception: 'stop-is-guarantee', feedback: 'Gaps and slippage can push the fill below the stop.' },
              { id: 'c', text: 'Costs don’t matter once a stop is set.', misconception: 'ignore-costs', feedback: 'Fees apply to every fill regardless of stops.' },
            ],
            explanation: 'Planned risk is before surprises. Actual loss = fill difference + slippage + fees.',
          },
        },
      ],
      recap: ['You sized a new plan, computed its ratio, and kept the stop’s limits in mind.'],
      glossary: ['risk-budget', 'reward-to-risk', 'slippage'],
      sources: ['finra-stop-orders'],
      review: { skills: ['position-sizing', 'reward-risk', 'costs-slippage'] },
      help: { simpler: 'Budget ÷ risk per share = shares. Reward ÷ risk = ratio. Costs make it worse.', example: 'Budget $20, risk $0.50/share → 40 shares.' },
    },
  ],
};
