import type { GlossaryTerm } from './schema';

export const GLOSSARY: GlossaryTerm[] = [
  { id: 'virtual-money', term: 'Virtual money', short: 'Pretend training money used in this app. It cannot be withdrawn, and no real trades happen.' },
  { id: 'share', term: 'Share', short: 'One unit of ownership in a company. Owning shares means owning a small slice of that company.', example: '2 shares at $10 each cost $20.' },
  { id: 'stock', term: 'Stock', short: 'Ownership in a company, divided into shares. Also called equity.' },
  { id: 'position', term: 'Position', short: 'The shares you currently hold in one company.' },
  { id: 'cost-basis', term: 'Cost basis', short: 'What you paid for a position: shares × purchase price (plus any fees).', example: '2 shares at $10 = $20 cost basis.' },
  { id: 'unrealized-gain', term: 'Unrealized gain or loss', short: 'The difference between what a position is worth now and what it cost. It is not locked in until you sell.', example: 'Bought at $20 total, now worth $24: $4 unrealized gain.' },
  { id: 'realized-gain', term: 'Realized gain or loss', short: 'The result that is locked in once you sell, after costs.' },
  { id: 'fee', term: 'Fee', short: 'A charge for placing a trade. This app uses a made-up training fee; real brokers differ.' },
  { id: 'investing', term: 'Investing', short: 'Buying assets to hold for a long time, usually years, toward a goal.' },
  { id: 'trading', term: 'Trading', short: 'Buying and selling more often to try to profit from shorter price moves. Riskier and more costly for beginners.' },
  { id: 'diversification', term: 'Diversification', short: 'Spreading money across different investments so one bad result hurts less. It reduces some risks but does not remove them.' },
  { id: 'bid', term: 'Bid', short: 'The highest price a buyer is offering right now. An immediate sell usually gets about this price.' },
  { id: 'ask', term: 'Ask', short: 'The lowest price a seller will accept right now. Also called the offer. An immediate buy usually pays about this price.' },
  { id: 'spread', term: 'Spread', short: 'The gap between the bid and the ask. Buying and then selling immediately loses about the spread.', example: 'Bid $9.99, ask $10.01: spread $0.02.' },
  { id: 'last-price', term: 'Last price', short: 'The price of the most recent trade. Your next trade may happen at a different price.' },
  { id: 'market-order', term: 'Market order', short: 'An order to buy or sell right away at the best available price. The fill is likely; the price is not guaranteed.' },
  { id: 'limit-order', term: 'Limit order', short: 'An order that sets your worst acceptable price. A buy limit fills only at that price or lower; it may never fill.' },
  { id: 'stop-order', term: 'Stop order', short: 'An order that waits for a trigger price, then becomes a market order. The fill can be worse than the trigger.' },
  { id: 'take-profit', term: 'Take-profit order', short: 'A sell limit above your entry that closes the position if price reaches your target.' },
  { id: 'oco', term: 'One-cancels-other', short: 'Two linked exit orders, such as a stop and a target. When one fills, the other is canceled.' },
  { id: 'gap', term: 'Gap', short: 'A jump between one price and the next with no trading in between, often at a new session after news.' },
  { id: 'slippage', term: 'Slippage', short: 'The difference between the price you expected and the price you got. This app adds a small adverse amount to market-style fills.' },
  { id: 'open', term: 'Open', short: 'The first price in a candle’s time period.' },
  { id: 'high', term: 'High', short: 'The highest price in a candle’s time period: the top of the upper wick.' },
  { id: 'low', term: 'Low', short: 'The lowest price in a candle’s time period: the bottom of the lower wick.' },
  { id: 'close', term: 'Close', short: 'The last price in a candle’s time period.' },
  { id: 'candle-body', term: 'Body', short: 'The thick part of a candle, between the open and the close.' },
  { id: 'wick', term: 'Wick', short: 'The thin lines above and below the body, reaching to the high and low. Also called shadows.' },
  { id: 'unchanged-candle', term: 'Unchanged candle', short: 'A candle whose close equals its open, so the body is a flat line. Often called a doji.' },
  { id: 'timeframe', term: 'Timeframe', short: 'How much time one candle covers, such as 5 minutes or 1 day.' },
  { id: 'uptrend', term: 'Uptrend', short: 'A series of higher highs and higher lows.' },
  { id: 'downtrend', term: 'Downtrend', short: 'A series of lower highs and lower lows.' },
  { id: 'range', term: 'Range', short: 'Sideways movement between a rough floor and ceiling.' },
  { id: 'swing-high', term: 'Swing high', short: 'A peak with lower highs on both sides. It can only be confirmed after later candles form.' },
  { id: 'swing-low', term: 'Swing low', short: 'A trough with higher lows on both sides. It can only be confirmed after later candles form.' },
  { id: 'volume', term: 'Volume', short: 'How many shares traded in a period. Every trade has a buyer and a seller, so volume does not show who “won”.' },
  { id: 'support', term: 'Support', short: 'A price area where falling prices have often paused. An area, not an exact line, and not a guarantee.' },
  { id: 'resistance', term: 'Resistance', short: 'A price area where rising prices have often stalled. An area, not an exact line, and not a guarantee.' },
  { id: 'breakout', term: 'Breakout', short: 'A move beyond a support or resistance area. Some continue; many fail.' },
  { id: 'failed-breakout', term: 'Failed breakout', short: 'A move beyond an area that quickly falls back inside it.' },
  { id: 'risk-budget', term: 'Risk budget', short: 'The most you plan to lose on one trade if your stop fills as expected. Actual losses can be larger.' },
  { id: 'reward-to-risk', term: 'Reward-to-risk', short: 'Potential reward divided by planned risk. It ignores how likely the target is.' },
  { id: 'trade-plan', term: 'Trade plan', short: 'A written plan made before a trade: entry, invalidation (stop), exit and size.' },
  { id: 'invalidation', term: 'Invalidation', short: 'The price that shows your trade idea was wrong. Your protective stop belongs there.' },
  { id: 'r-multiple', term: 'R multiple', short: 'A result measured in units of initial risk. Here: net result ÷ (entry fill − original stop) × shares.' },
  { id: 'fomo', term: 'FOMO', short: 'Fear of missing out: the urge to jump in because price is moving fast.' },
  { id: 'revenge-trading', term: 'Revenge trading', short: 'Trading right after a loss to “win it back”, often with more risk.' },
  { id: 'journal', term: 'Trading journal', short: 'A record of each plan, what happened and what you learned.' },
  { id: 'win-rate', term: 'Win rate', short: 'Winning trades divided by all trades. Meaningless without the size of wins and losses.' },
  { id: 'average-win', term: 'Average win', short: 'Total of winning trades divided by the number of wins.' },
  { id: 'average-loss', term: 'Average loss', short: 'Total of losing trades divided by the number of losses.' },
  { id: 'sample-size', term: 'Sample size', short: 'How many trades a statistic is based on. Small samples swing a lot by chance.' },
  { id: 'hypothesis', term: 'Hypothesis', short: 'A specific, testable guess that could turn out wrong.' },
  { id: 'hindsight-bias', term: 'Hindsight bias', short: 'Feeling that an outcome was obvious once you already know it.' },
  { id: 'equity', term: 'Equity (account)', short: 'Cash plus the current value of your position.' },
  { id: 'reserved-cash', term: 'Reserved cash', short: 'Cash set aside for a pending buy so it cannot be spent twice.' },
];

export const termById = (id: string) => GLOSSARY.find((t) => t.id === id);
